<!-- include(src/app_oauth.apib) -->
<!-- include(src/rest_api.apib) -->
<!-- include(src/rest_account.apib) -->
<!-- include(src/rest_customers.apib) -->
<!-- include(src/rest_customer_transactions.apib) -->
<!-- include(src/rest_customer_offers.apib) -->
<!-- include(src/rest_customer_coupons.apib) -->
<!-- include(src/rest_customer_actions.apib) -->
<!-- include(src/rest_customer_claimable_offers.apib) -->
<!-- include(src/rest_customer_rewards.apib) -->
<!-- include(src/rest_customer_consent.apib) -->
<!-- include(src/rest_customer_crm_fields.apib) -->
<!-- include(src/rest_customer_targeted_offers.apib) -->
<!-- include(src/rest_transactions.apib) -->
<!-- include(src/rest_transaction_details.apib) -->
<!-- include(src/rest_rewards.apib) -->
<!-- include(src/rest_product_rewards.apib) -->
<!-- include(src/rest_offers.apib) -->
<!-- include(src/rest_offer_images.apib) -->
<!-- include(src/rest_products.apib) -->
<!-- include(src/rest_branches.apib) -->
<!-- include(src/rest_tiers.apib) -->
<!-- include(src/rest_referral_programs.apib) -->
<!-- include(src/rest_business_rules.apib) -->
<!-- include(src/rest_workflows_triggers.apib) -->
<!-- include(src/rest_workflows_actions.apib) -->
<!-- include(src/rest_workflows.apib) -->
<!-- include(src/rest_reviews.apib) -->
