definitions:
  NotificationSettingsUpdateRequest:
    type: array
    x-model: NotificationSettingsUpdateRequest
    items:
      $ref: '#/definitions/NotificationSettingsData'
  NotificationSettingsModel:
    type: object
    x-model: NotificationSettingsModel
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/NotificationSettingsData'
  NotificationSettingsData:
    type: object
    properties:
      id:
        type: string
        description: |
          The notification settings id. This is not required
          when updating notification settings.
      business:
        $ref: '#/definitions/NotificationBusinessPayload'
      allow_email:
        type: boolean
      allow_sms:
        type: boolean
      allow_push:
        type: boolean
      allow_sms_status:
        type: integer
  NotificationBusinessPayload:
    type: object
    description: |
      The business who these settings this affect. This is not required
      when updating notification settings.
    properties:
      id:
        type: string
      name:
        type: string
      settings:
        $ref: '#/definitions/NotificationBusinessPayloadSettings'
  NotificationBusinessPayloadSettings:
    type: object
    description: |
        The settings of this business.
    properties:
      double_opt_in:
        type: boolean
