definitions:
  UserProducts:
    type: "object"
    x-model: UserProductsModel
    description: User Product model class containing user product list
    required:
      - data
      - included
    properties:
      data:
        description: "Contains all user data"
        $ref: "../users/userProfile.yaml#/definitions/UserProfileData"
      included:
        description: 'Contains products available to this user'
        $ref: '#/definitions/UserProductsIncluded'
  UserProductsIncluded:
    type: "object"
    required:
      - products
    properties:
      products:
        description:
        x-model:
        $ref: '#/definitions/ProductsList'
  ProductsList:
    type: array
    items:
      $ref: '#/definitions/Product'
  Product:
    type: "object"
    x-model: Product
    properties:
      id:
        type: integer
      title:
        type: string
      description:
        type: string
      images:
        type: array
        items:
          $ref: '#/definitions/Images'
      product_sku:
        type: string
      actual_price:
        type: number
        format: float
      real_price:
        type: number
        format: float
      terms_conditions:
        type: string
      link:
        type: string
      product_languages:
        type: array
        items:
          $ref: '#/definitions/Languages'
  Images:
    type: object
    properties:
      path:
        type: string
      large:
        type: string
      medium:
        type: string
      thumbnail:
        type: string
      default:
        type: boolean
  Languages:
    type: object
    properties:
      language_id:
        type: integer
      title:
        type: string
      description:
        type: string
      language:
        type: object
        x-model:
        $ref: './../languages/language.yaml'
  Error:
    type: "object"
    x-error: true
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  AlaCarteProducts:
    type: "object"
    x-model: AlaCarteProductsModel
    description: User A la carte products model class containing user A la carte list
    required:
      - data
      - included
    properties:
      data:
        description: "Contains all user data"
        $ref: "../users/userProfile.yaml#/definitions/UserProfileData"
      included:
        description: "Contains all A la carte items"
        $ref: '#/definitions/UserAlaCarteIncluded'
  UserAlaCarteIncluded:
    type: "object"
    required:
      - product_rewards
    properties:
      product_rewards:
        description:
        x-model:
        $ref: '#/definitions/AlaCarteList'
  AlaCarteList:
    type: array
    items:
      $ref: '#/definitions/AlaCarteItem'
  AlaCarteItem:
    type: "object"
    x-model: AlaCarteItemModel
    properties:
      id:
        type: integer
      points:
        type: integer
      product:
        description:
        $ref: '#/definitions/Product'