swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/me/businesses/{businessId}?include=branches:
    get:
      summary: Get the business associated with this user account and application
      operationId: getBusiness
      tags:
        - business
      parameters:
        - in: path
          name: businessId
          required: true
          type: string
      responses:
        "200":
          description: Business data
          schema:
            $ref: "schemas/business/business.yaml#/definitions/Business"