swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/me/messages/{depositId}:
    patch:
      summary: Deposit a giftcard
      operationId: depositGiftCard
      tags:
        - giftCardDeposit
      parameters:
        - in: path
          name: depositId
          required: true
          type: string
      responses:
        "200":
          description: Gift card deposit response
          schema:
            $ref: "schemas/messages/transferMessages.yaml#/definitions/TransferActionResultModel"