swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/me/draws?platform=mobile&relationships=prizes,branches:
    get:
      summary: Acquires business draws.
      operationId: getDraws
      tags:
        - draws
      responses:
        "200":
          description: Acquires business draws.
          schema:
            $ref: "schemas/draws/draws.yaml#/definitions/Draws"