swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/me/rewards/{rewardId}?include=external_products,external_product_variants&external_product_id={externalProductId}:
    get:
      summary: Get a reward with external product variants by external product id
      operationId: getAmazonProductVariants
      tags:
        - getAmazonProductVariants
      parameters:
        - in: path
          name: rewardId
          required: true
          type: integer
        - in: path
          name: externalProductId
          required: true
          type: string
      responses:
        "200":
          description: Reward with external product variants by external product id
          schema:
            $ref: 'schemas/rewards/rewards.yaml#/definitions/RewardResponse'