swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /public/crm-fields:
    get:
      summary: Get a list of the business crm fields
      operationId: getCrmFields
      tags:
        - CrmFields
      responses:
        "200":
          description: Crm Fields
          schema:
            $ref: "schemas/crmFields/crmFields.yaml#/definitions/CrmFields"