swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  public/campaigns/{campaignId}:
    get:
      summary: Get the offers / rewards for a related campaign
      operationId: getPublicCampaign
      tags:
        - getPublicCampaign
      parameters:
        - in: path
          name: campaignId
          required: true
          type: string
      responses:
        "200":
          description: campaign details
          schema:
            $ref: "schemas/publicCampaigns/publicCampaigns.yaml#/definitions/PublicCampaignsResponse"
