swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/me/giftcards:
    get:
      summary: Get a list of gift cards available for purchase
      operationId: getGiftCards
      tags:
        - giftCards
      responses:
        "200":
          description: User offer list
          schema:
            $ref: 'schemas/giftcards/giftCards.yaml#/definitions/GiftCardsResponse'