swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /public/rewards:
    get:
      summary: Get a list of rewards available to all users.
      operationId: getPublicRewards
      tags:
        - publicRewards
      responses:
        "200":
          description: Public rewards list
          schema:
            $ref: 'schemas/rewards/rewards.yaml#/definitions/PublicRewardsResponse'