swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /public/rewards/{rewardSlug}?relationships=branch:
    get:
      summary: Get a public reward
      operationId: getPublicReward
      tags:
        - publicReward
      parameters:
        - in: path
          name: rewardSlug
          required: true
          type: string
      responses:
        "200":
          description: Public reward
          schema:
            $ref: 'schemas/rewards/rewards.yaml#/definitions/PublicRewardResponse'