swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /public/branches?per_page={perPage}:
    get:
      summary: Get a list of branches available to all users.
      operationId: getPublicBranches
      tags:
        - publicBranches
      parameters:
        - in: path
          name: perPage
          type: integer
          default: 50
      responses:
        "200":
          description: Public branches list
          schema:
            $ref: 'schemas/business/business.yaml#/definitions/PublicBranches'