swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /public/app-strings:
    get:
      summary: Acquires application strings.
      operationId: getStrings
      tags:
        - strings
      responses:
        "200":
          description: Containts a list of application strings.
          schema:
            $ref: "schemas/strings/strings.yaml#/definitions/Strings"