swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/me/businesses/{businessId}/profile:
    patch:
      summary: update the last business chosen by the user in the conglomerate feature
      operationId: updateDefaultBusinessId
      tags:
        - updateDefaultBusinessId
      parameters:
        - in: path
          name: businessId
          required: true
          type: string
        - in: query
            name: default_business_id
            required: true
            schema:
              type: string
            description: id of the previous default business
      responses:
        "200":
          description: Business id
          schema:
            $ref: "schemas/defaultBusiness/defaultBusiness.yaml#/definitions/DefaultBusiness"