swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  mages:
    post:
      summary: upload an image
      operationId: uploadImage
      tags:
        - uploadImage
      consumes:
        - application/json
      parameters:
        - in: body
          name: uploadImageBodyRequest
          required: true
          schema:
            type: object
            $ref: 'schemas/uploadImages/uploadImages.yaml#/definitions/UploadImageRequest'
      responses:
        "200":
          description: upload an image
          schema:
            $ref: 'schemas/images/images.yaml#/definitions/ImagesResponse'
