swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/me/businesses/{businessId}?include=banners:
    get:
      summary: Acquires specific business banners.
      operationId: getUserBusinessBanners
      tags:
        - userBusinessBanners
      parameters:
        - in: path
          name: businessId
          required: true
          type: string
      responses:
        "200":
          description: Acquires business banners.
          schema:
            $ref: "schemas/banners/banners.yaml#/definitions/UserBusinessBanners"