swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/products:
    get:
      summary: Get user products list
      operationId: getUserProducts
      tags:
        - userProducts
      responses:
        "200":
          description: User products data
          schema:
            $ref: "schemas/products/products.yaml#/definitions/UserProducts"