swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/pincode/reset:
    post:
      summary: |
        Reset a customer PIN. Requires both a token and
        either a phone number or email address
      operationId: resetPinWithToken
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - userPinResetWithToken
      parameters:
        - in: body
          name: pinResetWithTokenRequest
          required: true
          schema:
            type: object
            $ref: '#/definitions/PinResetWithTokenRequest'
      responses:
        "200":
          description: |
            User PIN reset response.
definitions:
  PinResetWithTokenRequest:
    type: object
    x-model: PinResetWithTokenRequestModel
    required:
      - token
      - pin_code
      - use_same_pin
    properties:
      token:
        type: string
      pin_code:
        type: string
      use_same_pin:
        type: boolean