swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/me/coupons?per_page=50:
    get:
      summary: Get a list of available coupons for this user.
      operationId: getUserCoupons
      tags:
        - userCoupons
      responses:
        "200":
          description: User coupon list
          schema:
            $ref: 'schemas/coupons/coupons.yaml#/definitions/CouponsResponse'