swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/me:
    delete:
      summary: |
        Delete user account
      operationId: deleteUserAccount
      tags:
        - userDelete
      responses:
        "200":
          description: |
            Delete account request