swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/pincode/reset:
    post:
      summary: |
        Reset a customer PIN. Requires both a verification code and
        either a phone number or email address
      operationId: resetPin
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - userPinReset
      parameters:
        - in: formData
          name: verification_code
          required: true
          type: integer
        - in: formData
          name: pin_code
          required: true
          type: integer
        - in: formData
          name: email
          required: false
          type: string
        - in: formData
          name: phone
          required: false
          type: string
        - in: formData
          name: country_code
          required: false
          type: string
      responses:
        "200":
          description: |
            User PIN reset response.