swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/me/settings/notifications:
    put:
      summary: |
        Update a users notification settings.
        This will enable or disable push, sms, and or email
        notifications from the selected business.
      operationId: updateNotificationPreferences
      tags:
        - updateNotificationPreferences
      consumes:
        - application/json
      parameters:
        - in: body
          name: notificationPreferencesRequest
          description: The notification preferences update request.
          required: true
          schema:
            type: array
            items:
              $ref: "schemas/notificationSettings/notificationSettings.yaml#definitions/NotificationSettingsData"
      responses:
        "200":
          description: The users' updated balance.
          schema:
            $ref: 'schemas/notificationSettings/notificationSettings.yaml#/definitions/NotificationSettingsModel'