swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    post:
      summary: Register a new user. Either a phone number or an email address is required.
      operationId: createAccount
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - userRegistration
      parameters:
        - in: formData
          name: email
          required: false
          type: string
        - in: formData
          name: phone
          required: false
          type: string
        - in: formData
          name: country_code
          required: false
          type: string
        - in: formData
          name: language
          required: false
          type: string
      responses:
        "200":
          description: New user account details
          schema:
            $ref: "schemas/users/userProfile.yaml#/definitions/UserProfileData"