swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/me/businesses/{businessId}?include=products:
    get:
      summary: Get user products list by specific business
      operationId: getUserBusinessProducts
      tags:
        - userBusinessProducts
      parameters:
        - in: path
          name: businessId
          required: true
          type: string
      responses:
        "200":
          description: User products data
          schema:
            $ref: "schemas/products/products.yaml#/definitions/UserProducts"