swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/me/rewards:
    get:
      summary: Get a list of rewards available to this user.
      operationId: getUserRewards
      tags:
        - userRewards
      responses:
        "200":
          description: User rewards list
          schema:
            $ref: 'schemas/rewards/rewards.yaml#/definitions/RewardsResponse'