swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/me/transactions:
    post:
      summary: |
        Transfer points or e-wallet balance to another users
        account.
      operationId: transfer
      tags:
        - balanceTransfer
      consumes:
        - application/json
      parameters:
        - in: body
          name: transferRequest
          description: The transfer request.
          required: true
          schema:
            type: object
            $ref: 'schemas/transactions/transfer.yaml#/definitions/TransferResponse'
      responses:
        "200":
          description: The users' updated balance.