swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/me:
    get:
      summary: Get user details for this user.
      operationId: getUserDetails
      tags:
        - userDetails
      responses:
        "200":
          description: User details
          schema:
            $ref: "schemas/users/userProfile.yaml#/definitions/UserDetails"