# This is a dictionary of all endpoints used by the code generator
# All api spec files must be represented here as follows:
#
# "path" value is replaced "tags" value in the original spec
# "tags" parameter must have a single value of "core"
# This file will be used to generate code whenever all apis must be
# processed at once
swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api Dictionary
  license:
    name: MIT
consumes:
  - application/json
produces:
  - application/json
paths:
  strings:
    get:
      x-file: strings.yaml
      operationId: getStrings
      tags:
        - core
  businessRules:
    patch:
      x-file: businessRules.yaml
      operationId: getBusinessRules
      tags:
        - core
  updateBusinessRules:
    patch:
      x-file: updateBusinessRules.yaml
      operationId: updateBusinessRules
      tags:
        - core
  businessActiveOffers:
    patch:
      x-file: businessActiveOffers.yaml
      operationId: getBusinessActiveOffers
      tags:
        - core
  businessInActiveOffers:
    patch:
      x-file: businessInActiveOffers.yaml
      operationId: getBusinessInActiveOffers
      tags:
        - core
  businessActiveRewards:
    patch:
      x-file: businessActiveRewards.yaml
      operationId: getBusinessActiveRewards
      tags:
        - core
  businessInActiveRewards:
    patch:
      x-file: businessInActiveRewards.yaml
      operationId: getBusinessInActiveRewards
      tags:
        - core
  businessOfferById:
    patch:
      x-file: businessOfferById.yaml
      operationId: getBusinessOfferById
      tags:
        - core
  businessRewardById:
    patch:
      x-file: businessRewardById.yaml
      operationId: getBusinessRewardById
      tags:
        - core
  deleteOfferById:
    patch:
      x-file: deleteOfferById.yaml
      operationId: deleteOfferById
      tags:
        - core
  deleteRewardById:
    patch:
      x-file: deleteRewardById.yaml
      operationId: deleteRewardById
      tags:
        - core
  getUserDetails:
    patch:
      x-file: getUserDetails.yaml
      operationId: getUserDetails
      tags:
        - core
  createBusinessOffer:
    post:
      x-file: createBusinessOffer.yaml
      operationId: createBusinessOffer
      tags:
        - core
  updateBusinessOffer:
    patch:
      x-file: updateBusinessOffer.yaml
      operationId: updateBusinessOffer
      tags:
        - core
  createBusinessReward:
    post:
      x-file: createBusinessReward.yaml
      operationId: createRewardRequest
      tags:
        - core
  updateBusinessReward:
    patch:
      x-file: updateBusinessReward.yaml
      operationId: updateBusinessReward
      tags:
        - core
  businessRecommendations:
    patch:
      x-file: businessRecommendations.yaml
      operationId: getBusinessRecommendations
      tags:
        - core
  deleteRecommendationById:
    patch:
      x-file: deleteRecommendationById.yaml
      operationId: deleteRecommendationById
      tags:
        - core
  businessCampaigns:
    get:
      x-file: businessCampaigns.yaml
      operationId: getBusinessCampaigns
      tags:
        - core
  businessCampaignById:
    get:
      x-file: businessCampaignById.yaml
      operationId: getBusinessCampaignById
      tags:
        - core
  userDeviceToken:
    get:
      x-file: userDeviceToken.yaml
      operationId: updateUserDeviceToken
      tags:
        - core
  businessNotifications:
    get:
      x-file: businessNotifications.yaml
      operationId: getBusinessNotifications
      tags:
        - core
  updateNotificationById:
    put:
      x-file: updateNotificationById.yaml
      operationId: updateNotificationById
      tags:
        - core
  createBusinessCampaign:
    post:
      x-file: createBusinessCampaign.yaml
      operationId: createBusinessCampaign
      tags:
        - core
  businessCampaignAudience:
    get:
      x-file: businessCampaignAudience.yaml
      operationId: getBusinessCampaignAudience
      tags:
        - core
  deleteCampaignById:
    patch:
      x-file: deleteCampaignById.yaml
      operationId: deleteCampaignById
      tags:
        - core
  businessTags:
    get:
      x-file: businessTags.yaml
      operationId: getBusinessTags
      tags:
        - core
  businessSegments:
    get:
      x-file: businessSegments.yaml
      operationId: getBusinessSegments
      tags:
        - core
  updateBusinessCampaign:
    post:
      x-file: updateBusinessCampaign.yaml
      operationId: updateBusinessCampaign
      tags:
        - core
  businessTiers:
    get:
      x-file: businessTiers.yaml
      operationId: getBusinessTiers
      tags:
        - core
  getResetPasswordToken:
    post:
      x-file: getResetPasswordToken.yaml
      operationId: getResetPasswordToken
      tags:
        - core
  businessShopifyProducts:
    get:
      x-file: businessShopifyProducts.yaml
      operationId: getBusinessShopifyProducts
      tags:
        - core
  businessShopifyVendors:
    get:
      x-file: businessShopifyVendors.yaml
      operationId: getBusinessShopifyVendors
      tags:
        - core
  businessShopifyProductsTags:
    get:
      x-file: businessShopifyProductsTags.yaml
      operationId: getBusinessShopifyProductsTags
      tags:
        - core
  businessShopifyCategories:
    get:
      x-file: businessShopifyCategories.yaml
      operationId: getBusinessShopifyCategories
      tags:
        - core
  businessSettingsIntegrations:
    get:
      x-file: businessSettingsIntegrations.yaml
      operationId: getBusinessSettingsIntegrations
      tags:
        - core
  createBusinessTargetedOffer:
    post:
      x-file: createBusinessTargetedOffer.yaml
      operationId: createBusinessTargetedOffer
      tags:
        - core
  createBusinessTargetedReward:
    post:
      x-file: createBusinessTargetedReward.yaml
      operationId: createBusinessTargetedReward
      tags:
        - core
  businessOfferAudience:
    post:
      x-file: businessOfferAudience.yaml
      operationId: getBusinessOfferAudience
      tags:
        - core
  businessRewardAudience:
    post:
      x-file: businessRewardAudience.yaml
      operationId: getBusinessRewardAudience
      tags:
        - core
  businessCallToAction:
    get:
      x-file: businessCallToAction.yaml
      operationId: getBusinessCallToAction
      tags:
        - core
  updateBusinessCallToAction:
    patch:
      x-file: updateBusinessCallToAction.yaml
      operationId: updateBusinessCallToAction
      tags:
        - core
  businessPinnedModules:
    get:
      x-file: businessPinnedModules.yaml
      operationId: getBusinessPinnedModules
      tags:
        - core
  updateBusinessPinnedModules:
    patch:
      x-file: updateBusinessPinnedModules.yaml
      operationId: updateBusinessPinnedModules
      tags:
        - core
  registerAsLead:
    post:
      x-file: registerAsLead.yaml
      operationId: registerAsLead
      tags:
        - core
  businessALaCarteProducts:
    get:
      x-file: businessALaCarteProducts.yaml
      operationId: getBusinessALaCarteProducts
      tags:
        - core
#  uploadBusinessOfferImage:
#    patch:
#      x-file: uploadBusinessOfferImage.yaml
#      operationId: uploadBusinessOfferImage
#      tags:
#        - core
  requestResetPassword:
    get:
      x-file: requestResetPassword.yaml
      operationId: requestResetPassword
      tags:
        - core
  createNewPassword:
    get:
      x-file: createNewPassword.yaml
      operationId: createNewPassword
      tags:
        - core
  businessCampaignsDateRange:
    get:
      x-file: businessCampaignsDateRange.yaml
      operationId: getBusinessCampaignsDateRange
      tags:
        - core
  businessActiveOffersDateRange:
    get:
      x-file: businessActiveOffersDateRange.yaml
      operationId: getBusinessActiveOffersDateRange
      tags:
        - core
  businessActiveRewardsDateRange:
    get:
      x-file: businessActiveRewardsDateRange.yaml
      operationId: getBusinessActiveRewardsDateRange
      tags:
        - core
  businessCustomerById:
    get:
      x-file: businessCustomerById.yaml
      operationId: getBusinessCustomerById
      tags:
        - core
  businessCustomers:
    get:
      x-file: businessCustomers.yaml
      operationId: getBusinessCustomers
      tags:
        - core
  createBusinessCustomer:
    post:
      x-file: createBusinessCustomer.yaml
      operationId: createBusinessCustomer
      tags:
        - core
  updateBusinessCustomer:
    patch:
      x-file: updateBusinessCustomer.yaml
      operationId: updateBusinessCustomer
      tags:
        - core
  countries:
    get:
      x-file: countries.yaml
      operationId: getCountries
      tags:
        - core
  businessLoyaltyGeneratedRevenueDaily:
    get:
      x-file: businessLoyaltyGeneratedRevenueDaily.yaml
      operationId: getBusinessDailyLoyaltyGeneratedRevenue
      tags:
        - core
  businessLoyaltyGeneratedRevenueMonthly:
    get:
      x-file: businessLoyaltyGeneratedRevenueMonthly.yaml
      operationId: getBusinessMonthlyLoyaltyGeneratedRevenue
      tags:
        - core
  businessTotalSignUpDaily:
    get:
      x-file: businessTotalSignUpDaily.yaml
      operationId: getBusinessDailyTotalSignUp
      tags:
        - core
  businessTotalSignUpMonthly:
    get:
      x-file: businessTotalSignUpMonthly.yaml
      operationId: getBusinessMonthlyTotalSignUp
      tags:
        - core
  businessTouchPointsDaily:
    get:
      x-file: businessTouchPointsDaily.yaml
      operationId: getBusinessDailyTouchPoints
      tags:
        - core
  businessTouchPointsMonthly:
    get:
      x-file: businessTouchPointsMonthly.yaml
      operationId: getBusinessMonthlyTouchPoints
      tags:
        - core