# This is a dictionary of all endpoints used by the code generator
# All api spec files must be represented here as follows:
#
# "path" value is replaced "tags" value in the original spec
# "tags" parameter must have a single value of "core"
# This file will be used to generate code whenever all apis must be
# processed at once
swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api Dictionary
  license:
    name: MIT
consumes:
  - application/json
produces:
  - application/json
paths:
  strings:
    get:
      x-file: strings.yaml
      operationId: getStrings
      tags:
        - core
  businessRules:
    patch:
      x-file: businessRules.yaml
      operationId: getBusinessRules
      tags:
        - core
  updateBusinessRules:
    patch:
      x-file: updateBusinessRules.yaml
      operationId: updateBusinessRules
      tags:
        - core
  businessActiveOffers:
    patch:
      x-file: businessActiveOffers.yaml
      operationId: getBusinessActiveOffers
      tags:
        - core
  businessInActiveOffers:
    patch:
      x-file: businessInActiveOffers.yaml
      operationId: getBusinessInActiveOffers
      tags:
        - core
  businessActiveRewards:
    patch:
      x-file: businessActiveRewards.yaml
      operationId: getBusinessActiveRewards
      tags:
        - core
  businessInActiveRewards:
    patch:
      x-file: businessInActiveRewards.yaml
      operationId: getBusinessInActiveRewards
      tags:
        - core
  businessOfferById:
    patch:
      x-file: businessOfferById.yaml
      operationId: getBusinessOfferById
      tags:
        - core
  businessRewardById:
    patch:
      x-file: businessRewardById.yaml
      operationId: getBusinessRewardById
      tags:
        - core
  deleteOfferById:
    patch:
      x-file: deleteOfferById.yaml
      operationId: deleteOfferById
      tags:
        - core
  deleteRewardById:
    patch:
      x-file: deleteRewardById.yaml
      operationId: deleteRewardById
      tags:
        - core
  getUserDetails:
    patch:
      x-file: getUserDetails.yaml
      operationId: getUserDetails
      tags:
        - core
  createBusinessOffer:
    patch:
      x-file: createBusinessOffer.yaml
      operationId: createBusinessOffer
      tags:
        - core
  updateBusinessOffer:
    patch:
      x-file: updateBusinessOffer.yaml
      operationId: updateBusinessOffer
      tags:
        - core
  createBusinessReward:
    patch:
      x-file: createBusinessReward.yaml
      operationId: createRewardRequest
      tags:
        - core
  updateBusinessReward:
    patch:
      x-file: updateBusinessReward.yaml
      operationId: updateBusinessReward
      tags:
        - core
  businessRecommendations:
    patch:
      x-file: businessRecommendations.yaml
      operationId: getBusinessRecommendations
      tags:
        - core
  deleteRecommendationById:
    patch:
      x-file: deleteRecommendationById.yaml
      operationId: deleteRecommendationById
      tags:
        - core
  businessCampaigns:
    patch:
      x-file: businessCampaigns.yaml
      operationId: getBusinessCampaigns
      tags:
        - core