swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /segments?per_page=50:
    get:
      summary: Get a list of business segments
      operationId: getBusinessSegments
      tags:
        - businessSegments
      responses:
        "200":
          description: Business segments list
          schema:
            $ref: 'schemas/businessSegments/businessSegments.yaml#/definitions/SegmentsResponse'