swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /offers:
    get:
      summary: Get a list of business offers
      operationId: getBusinessOffers
      tags:
        - businessOffers
      responses:
        "200":
          description: Business offer list
          schema:
            $ref: 'schemas/businessOffers/businessOffers.yaml#/definitions/OffersResponse'