swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /tiers?relationships=tier_levels:
    get:
      summary: Get a list of business tiers
      operationId: getBusinessTiers
      tags:
        - businessTiers
      responses:
        "200":
          description: Business tiers list
          schema:
            $ref: 'schemas/businessTiers/businessTiers.yaml#/definitions/TiersResponse'