swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /customers/{customerId}?include=balance,tier_progress,tier_level,consent,note:
    get:
      summary: Get a customer by its id
      operationId: getBusinessCustomerById
      tags:
        - businessCustomerById
      parameters:
        - in: path
          name: customerId
          required: true
          type: string
      responses:
        "200":
          description: customer by its id
          schema:
            $ref: 'schemas/businessCustomers/businessCustomers.yaml#/definitions/CustomerResponse'