swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/v1/integrations/{posSystemPk}/branch-links :
    get:
      summary: Retrieves the business's integrations branch links
      operationId: getBusinessIntegrationBranchLinks
      x-server-host-id: 1
      tags:
        - businessIntegrationBranchLinks
      parameters:
        - in: path
          name: posSystemPk
          required: true
          type: integer
      responses:
        "200":
          description: Retrieved the business's integrations branch links
          schema:
            $ref: "schemas/businessIntegrationBranchLinks/businessIntegrationBranchLinks.yaml#/definitions/BusinessIntegrationsBranchLinksResponse"