swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  campaigns/{campaignId}?include=summary,statistics:
    get:
      summary: Get a campaign by its id
      operationId: getBusinessCampaignById
      tags:
        - businessCampaignById
      parameters:
        - in: path
          name: campaignId
          required: true
          type: integer
      responses:
        "200":
          description: Business campaign by its id
          schema:
            $ref: 'schemas/businessCampaigns/businessCampaigns.yaml#/definitions/CampaignByIdResponse'