swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /shopify/searchProducts?store={shopifyStoreId}&scope={scope}:
    get:
      summary: Retrieves the business's categories on shopify
      operationId: getBusinessShopifyCategories
      x-is-integration: true
      tags:
        - businessShopifyCategories
      parameters:
        - in: path
          name: shopifyStoreId
          required: true
          type: string
        - in: path
          name: scope
          required: false
          type: string
      responses:
        "200":
          description: Retrieved business's categories on shopify
          schema:
            $ref: "schemas/businessShopifyCategories/businessShopifyCategories.yaml#/definitions/BusinessShopifyCategoriesResponse"