swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /rules:
    get:
      summary: Get the business's rules
      operationId: getBusinessRules
      tags:
        - businessRules
      responses:
        "200":
          description: Business rules
          schema:
            $ref: "schemas/business/businessRules.yaml#/definitions/BusinessesRules"