swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /rewards?status=inactive&per_page=50:
    get:
      summary: Get a list of business rewards that are inactive
      operationId: getBusinessInActiveRewards
      tags:
        - businessInActiveRewards
      responses:
        "200":
          description: Business inactive reward list
          schema:
            $ref: 'schemas/businessRewards/businessRewards.yaml#/definitions/RewardsResponse'