swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /business-settings?include=integrations,languages:
    get:
      summary: Get the business's settings and integrations
      operationId: getBusinessSettingsIntegrations
      tags:
        - businessSettingsIntegrations
      responses:
        "200":
          description: Business settings and integrations
          schema:
            $ref: "schemas/businessSettingsIntegrations/businessSettingsIntegrations.yaml#/definitions/BusinessSettingsIntegrations"