swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /insights/touch-points?days_back={daysCount}:
    get:
      summary: Get a list of total touch points by day
      operationId: getBusinessDailyTouchPointsInsight
      tags:
        - businessDailyTouchPoints
      parameters:
        - in: path
          name: daysCount
          required: true
          type: integer
      responses:
        "200":
          description: List of total touch points by day
          schema:
            $ref: 'schemas/businessInsights/businessInsights.yaml#/definitions/TouchPointsResult'