swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  magento/products?domain={magentoDomain}&sku={sku}:
    get:
      summary: Retrieves the business's products on magento
      operationId: getBusinessMagentoProducts
      x-server-host-id: 1
      tags:
        - businessMagentoProducts
      parameters:
        - in: path
          name: magentoDomain
          required: true
          type: string
        - in: path
          name: sku
          required: true
          type: string
      responses:
        "200":
          description: Retrieved business's products on magento
          schema:
            $ref: "schemas/businessIntegrationsProducts/businessIntegrationsProducts.yaml#/definitions/BusinessIntegrationsProductsResponse"
