swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /campaigns?per_page={perPage}:
    get:
      summary: Get a list of business marketing campaigns
      operationId: getBusinessCampaigns
      tags:
        - businessCampaigns
      parameters:
        - in: path
          name: perPage
          type: integer
          default: 50
      responses:
        "200":
          description: Business marketing campaigns
          schema:
            $ref: 'schemas/businessCampaigns/businessCampaigns.yaml#/definitions/CampaignsResponse'