swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /customers?include=tier_level&customer_segments=in|{segmentId}&order_first=asc&per_page={perPage}&page={pageNumber}:
    get:
      summary: Get a list of business customers by segment
      operationId: getBusinessCustomersBySegment
      tags:
        - businessCustomersBySegment
      parameters:
        - in: path
          name: segmentId
          required: true
          type: string
        - in: path
          name: perPage
          required: true
          type: integer
        - in: path
          name: pageNumber
          required: true
          type: integer
      responses:
        "200":
          description: list of customers by segment
          schema:
            $ref: 'schemas/businessCustomers/businessCustomers.yaml#/definitions/CustomersResponse'