swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /tags?per_page=50:
    get:
      summary: Get a list of business tags
      operationId: getBusinessTags
      tags:
        - businessTags
      responses:
        "200":
          description: Business tags list
          schema:
            $ref: 'schemas/businessTags/businessTags.yaml#/definitions/TagsResponse'