swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /campaigns/audience?include=reachable,unreachable,targeted:
    post:
      summary: Get audience data of a marketing campaign
      operationId: getBusinessCampaignAudience
      consumes:
        - application/json
      tags:
        - businessCampaignAudience
      parameters:
        - in: body
          name: getBusinessCampaignAudienceRequest
          required: true
          schema:
            type: object
            $ref: 'schemas/campaignAudience/campaignAudience.yaml#/definitions/GetCampaignAudienceRequest'
      responses:
        "200":
          description: |
            The result of getting audience of a marketing campaign
          schema:
            $ref: 'schemas/campaignAudience/campaignAudience.yaml#/definitions/GetCampaignAudienceResponse'