swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /recommendations:
    get:
      summary: Retrieves recommendations related to this business
      operationId: getBusinessRecommendations
      tags:
        - businessRecommendations
      responses:
        "200":
          description: retrieves recommendations related to this business
          schema:
            $ref: "schemas/businessRecommendations/businessRecommendations.yaml#/definitions/BusinessRecommendationsResponse"