swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /campaigns:
    post:
      summary: |
        Create a marketing campaign
      operationId: createBusinessCampaign
      consumes:
        - application/json
      tags:
        - createBusinessCampaign
      parameters:
        - in: body
          name: createCampaignRequest
          required: true
          schema:
            type: object
            $ref: 'schemas/businessCampaigns/createUpdateCampaign.yaml#/definitions/CreateUpdateCampaignRequest'
      responses:
        "200":
          description: |
            The result of creating a marketing campaign
          schema:
            $ref: 'schemas/businessCampaigns/createUpdateCampaign.yaml#/definitions/CreateUpdateCampaignResponse'