swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /password/reset:
    post:
      summary: create a new password
      operationId: createNewPassword
      consumes:
        - application/json
      tags:
        - createNewPassword
      parameters:
        - in: body
          name: createNewPasswordBodyRequest
          description: new password to be created
          required: true
          schema:
            type: object
            required:
              - token
              - password
              - password_confirmation
            properties:
              token:
                type: string
              password:
                type: string
              password_confirmation:
                type: string
      responses:
        "204":
          description: created new password