swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  customers/{customerId}/crm-fields:
    get:
      summary: Get a customer's crm fields
      operationId: getCustomerCrmFields
      tags:
        - customerCrmFields
      parameters:
        - in: path
          name: customerId
          type: string
          required: true
      responses:
        "200":
          description: A customer's crm fields
          schema:
            $ref: 'schemas/businessCustomers/crmFields.yaml#/definitions/CrmFieldsResponse'