swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /offers/{offerId}:
    delete:
      summary: delete an offer by its id
      operationId: deleteOfferById
      tags:
        - deleteOfferById
      parameters:
        - in: path
          name: offerId
          required: true
          type: integer
      responses:
        "204":
          description: delete an offer by its id