swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /recommendations/{recommendationId}:
    delete:
      summary: delete a recommendation by its id
      operationId: deleteRecommendationById
      tags:
        - deleteRecommendationById
      parameters:
        - in: path
          name: recommendationId
          required: true
          type: integer
      responses:
        "204":
          description: delete a recommendation by its id