swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /rewards/{rewardId}:
    delete:
      summary: delete a reward by its id
      operationId: deleteRewardById
      tags:
        - deleteRewardById
      parameters:
        - in: path
          name: rewardId
          required: true
          type: integer
      responses:
        "204":
          description: delete a reward by its id
          schema:
            $ref: "#/definitions/DeleteResult"
definitions:
  DeleteResult:
    type: "object"