swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /oauth/token:
    post:
      summary: Retrieves a token used upon resetting user password
      operationId: getResetPasswordToken
      tags:
        - getResetPasswordToken
      parameters:
        - in: body
          name: grant_type
          required: true
          type: string
        - in: body
          name: client_id
          required: true
          type: string
        - in: body
          name: client_secret
          required: true
          type: string
      responses:
        "200":
          description: |
            Returned token used upon resetting user password
          schema:
            $ref: '#/definitions/ResetPasswordToken'
definitions:
  ResetPasswordToken:
    type: "object"
    x-model: ResetPasswordTokenModel
    description: User PIN reset request status
    required:
      - token_type
      - expires_in
      - access_token
    properties:
      token_type:
        type: string
      expires_in:
        type: string
      access_token:
        type: string