swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /password/reset-request:
    post:
      summary: request to reset password
      operationId: requestResetPassword
      consumes:
        - application/json
      tags:
        - requestResetPassword
      parameters:
        - in: body
          name: requestResetPasswordBodyRequest
          description: email to receive reset link on
          required: true
          schema:
            type: object
            required:
              - email
            properties:
              token:
                email: string
      responses:
        "202":
          description: requested to reset password
