swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /rules:
    patch:
      summary: update business's rules
      operationId: updateBusinessRules
      consumes:
        - application/json
      tags:
        - updateBusinessRules
      parameters:
        - in: body
          name: updateBusinessRulesBodyRequest
          required: true
          schema:
            type: object
            required:
              - reward_ratio
              - reward_milestone_amount
              - welcome_points
            properties:
              reward_ratio:
                type: number
                format: double
                description: points earned by user after spending x amount
              reward_milestone_amount:
                type: integer
                format: int64
                description: amount to be spent by user to earn x points
              welcome_points:
                type: integer
                format: int64
                description: sign up bonus
      responses:
        "200":
          description: Business rules
          schema:
            $ref: "schemas/businessRules/businessRules.yaml#/definitions/BusinessesRules"