swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Customer Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /app-modules:
    patch:
      summary: update business's pinned modules
      operationId: updateBusinessPinnedModules
      consumes:
        - application/json
      tags:
        - updateBusinessPinnedModules
      parameters:
        - in: body
          name: updatePinnedModulesRequest
          required: true
          schema:
            type: object
            $ref: 'schemas/businessPinnedModules/businessPinnedModules.yaml#/definitions/UpdatePinnedModulesRequest'
      responses:
        "200":
          schema:
            $ref: "schemas/businessPinnedModules/businessPinnedModules.yaml#/definitions/BusinessPinnedModulesResponse"