swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /notifications/{notificationId}:
    put:
      summary: delete a recommendation by its id
      operationId: updateNotificationById
      tags:
        - updateNotificationById
      parameters:
        - in: path
          name: notificationId
          required: true
          type: integer
        - in: body
          name: updateNotificationRequest
          required: true
          schema:
            type: object
            $ref: 'schemas/businessNotifications/updateNotification.yaml#/definitions/UpdateNotificationRequest'
      responses:
        "200":
          schema:
            $ref: "schemas/businessNotifications/updateNotification.yaml#/definitions/UpdateNotificationResponse"