swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
  - multipart/form-data
produces:
  - application/json
paths:
  /offers/images:
    post:
      summary: upload images of an offer
      operationId: uploadBusinessOfferImage
      tags:
        - uploadBusinessOfferImage
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: image_large
          type: file
          required: true
        - in: formData
          name: image_original
          type: file
          required: true
        - in: formData
          name: image_medium
          type: file
          required: true
        - in: formData
          name: image_thumbnail
          type: file
          required: true
      responses:
        "200":
          description: uploaded images of an offer
          schema:
            $ref: 'schemas/images/images.yaml#/definitions/ImagesResponse'
