swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
  - multipart/form-data
produces:
  - application/json
paths:
  /offers/images:
    post:
      summary: upload images of an offer
      operationId: uploadBusinessOfferImage
      tags:
        - uploadBusinessOfferImage
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: image_large
          schema:
            type: object
            schema:
              type: object
              required:
                - intent
                - branch_id
                - catalog_items
              properties:
                branch_id:
                  type: string
                intent:
                  type: string
                  default: "redeem"
          required: true
        - in: formData
          name: image_original
          type: string
        - in: formData
          name: image_medium
          schema:
            $ref: 'schemas/images/images.yaml#/definitions/KRMultiPartFormFile'
        - in: formData
          name: image_thumbnail
          schema:
            type: object
            $ref: 'schemas/images/images.yaml#/definitions/KRMultiPartFormFile'
      responses:
        "200":
          description: uploaded images of an offer
          schema:
            $ref: 'schemas/images/images.yaml#/definitions/ImagesResponse'
