swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  attachments:
    post:
      summary: upload images of a campaign
      operationId: uploadBusinessCampaignImage
      tags:
        - uploadBusinessCampaignImage
      consumes:
        - application/json
      parameters:
        - in: body
          name: uploadBusinessCampaignImageBodyRequest
          required: true
          schema:
            type: object
            $ref: 'schemas/uploadImages/uploadImages.yaml#/definitions/UploadImageRequest'
      responses:
        "200":
          description: uploaded images of a campaign
          schema:
            $ref: 'schemas/images/images.yaml#/definitions/ImagesResponse'
