swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /rewards/images:
    post:
      summary: upload images of a reward
      operationId: uploadBusinessRewardImage
      tags:
        - uploadBusinessRewardImage
      consumes:
        - application/json
      parameters:
        - in: body
          name: uploadBusinessRewardImageBodyRequest
          required: true
          schema:
            type: object
            $ref: 'schemas/uploadImages/uploadImages.yaml#/definitions/UploadImageRequest'
      responses:
        "200":
          description: uploaded images of a reward
          schema:
            $ref: 'schemas/images/images.yaml#/definitions/ImagesResponse'
