swagger: "2.0"
info:
  version: 1.0.0
  title: Kangaroo Business Api
  license:
    name: MIT
host: com.kangaroo.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /offers/images:
    post:
      summary: upload images of an offer
      operationId: uploadBusinessOfferImage
      tags:
        - uploadBusinessOfferImage
      consumes:
        - application/json
      parameters:
        - in: body
          name: uploadBusinessOfferImageRequest
          required: true
          schema:
            type: object
            $ref: 'schemas/uploadImages/uploadImages.yaml#/definitions/UploadImageRequest'
      responses:
        "200":
          description: uploaded images of an offer
          schema:
            $ref: 'schemas/images/images.yaml#/definitions/ImagesResponse'
