FORMAT: 1A
HOST: https://api.kangaroorewards.com

# Kangaroo Rewards - API Reference

>**Note.**
If you are looking for Users API Reference, it is available at [User API Reference](https://api.kangaroorewards.com/docs/user)

The Kangaroo Rewards API uses HTTP methods and a RESTful endpoint structure. The API authorization framework is OAuth 2.0. You format requests in JSON and the APIs return JSON-formatted responses.

Developers can build an app using Kangaroo Rewards API in their language of choice. To simplify integrations, Kangaroo Rewards provides REST Server SDKs and samples available on Github (in PHP).

[KangarooRewards-PHP-SDK](https://github.com/kangaroorewards/KangarooRewards-PHP-SDK) - the SDK without Oauth2 support (you will need to handle authentication and request an access token using another [library](https://github.com/kangaroorewards/oauth2-kangaroo-rewards), or by making API calls directly to the authentication endpoints)

[OAuth2 Kangaroo Rewards](https://github.com/kangaroorewards/oauth2-kangaroo-rewards) - the OAuth2 Client for Kangaroo Rewards API

[REST API sample App](https://github.com/kangaroorewards/rest-api-sample-app-php) - a sample app built in PHP using the SDK: [KangarooRewards-PHP-SDK](https://github.com/kangaroorewards/KangarooRewards-PHP-SDK) and OAuth2 client: [OAuth2 Kangaroo Rewards](https://github.com/kangaroorewards/oauth2-kangaroo-rewards) that helps you to build your app faster.

[Tutorials](https://github.com/kangaroorewards/api-docs/wiki) - A list of the most common use cases with step-by-step instructions

[Kangaroo Rewards API GPT](https://chatgpt.com/g/g-690e5437101081918dcc2a7ea560b3af-kangaroo-rewards-api) - Explore the Kangaroo Rewards API GPT through ChatGPT, ask questions, get an answers, and generate code in an instant!

## Build Your First App Following These Steps

- Step 1: Register an app with Kangaroo Rewards
- Step 2: Implement Authentication
- Step 3: Access Kangaroo Rewards REST API

>**Prerequisite.**
To get started, you will need a Kangaroo Rewards Developer account with which to build and test your app.
Sign up for free at: api.kangaroorewards.com/developers

### App capabilities

Your app can do these things and more.

- Access your account information
- Access Business information including branches, offers, rewards etc.
- List all Customers and new Customers
- Reward your customers
- List Custom Rewards and Catalog Items
- Redeem based on amount, points or Catalog Item

The following steps show how your application interacts with Kangaroo's OAuth 2.0 server 
to obtain a user's consent to perform an API request on the user's behalf. Your application 
must have that consent before it can execute a Kangaroo API request that requires user 
authorization.

The list below quickly summarizes these steps:

- Your application identifies the permissions it needs.
- Your application redirects the user to Kangaroo Rewards along with the list of requested permissions.
- The user decides whether to grant the permissions to your application.
- Your application finds out what the user decided.
- If the user granted the requested permissions, your application retrieves tokens needed to make API requests on the user's behalf.


### Register an app with Kangaroo Rewards

Go to [Developer Portal](https://api.kangaroorewards.com/developers/applications "Developer Portal").
Click on the “Register a new Application” button. Consider using a service account when registering your app at
[Developer Portal](https://api.kangaroorewards.com/developers/applications "Developer Portal"). i.e. “apps@yourcompany.com” -
This will ensure your app continues to work if you or the app creator leaves the company.

|Register a New App - Fields|Description|
|-----|-----------|
|Application name|The app name which will appear on Authorization dialog.|
|Authorization callback URL|This must be the page url where the users will be redirected after authorizing your application. Also, The Access Token will be sent to this page|
|Application description|Optional. This is what the users will see on Authentication page|

<img src="https://api.kangaroorewards.com/img/app1.png" title="Register your app" style="width: 100%;">

Once the application is created, it will have a Client ID and Client Secret associated to it. The Client ID is public, but Client Secret must not be shared.

>**Note:**
> By default, the application you recently created is **NOT Approved**. Please contact Kangaroo Rewards Support 
> and get the application **APPROVED** before continuing with the Authentication implementation.


After you finished building your app and tested it, you may request authorization from the person you are developing the application. He/She will normally be a Business Owner and will receive an email with authorization link.

<img src="https://api.kangaroorewards.com/img/app2.png" title="Request Authorization" style="width: 100%;">

>**Note:**
OAuth state is a random string that is optional, but highly recommended to mitigate CSRF attacks.
If you decide to use state parameter in your app and request authorization by email, you have to store the state parameter value in your callback page. A sample code for callback page can be found [here](https://gist.github.com/kangaroodev/5d33c691d5e7801d00ed31bfb0c76441)


### Implement Authentication

OAuth 2 is an open standard for authorization that enables third-party applications to obtain limited access to Kangaroo Rewards merchant accounts, by delegating user authentication to Kangaroo Rewards.

All developers need to register their application before getting started. A registered OAuth application is assigned a unique Client ID and Client Secret. The Client Secret should not be shared.

Currently Kangaroo Rewards API supports 2 types of authorization:

- <a href="#header-oauth-web-application-flow">Web Application Flow (or Authorization Code flow)</a>
- <a href="#header-oauth-password-credentials-grant">Password Credentials Grant (or Resource Owner Credentials)</a>

>**NOTE:**
>When creating a new application please make sure to select the corresponding grant type for your application
>- For `Authorization Code` flow the Grant Type MUST be **Authorization Code**
>- For `Resource Owner Credentials` flow the Grant Type MUST be **Password Grant**

#### OAuth - Web Application Flow

The Kangaroo Rewards OAuth API supports the Authorization Code flow, which is suitable for web applications running on a server. This is a description of the flow for third party applications.

This scenario begins by redirecting a browser (full page or popup) to a Kangaroo Rewards URL with a set of query parameters that indicate the type of Kangaroo Rewards API access the application requires. As in other scenarios, Kangaroo Rewards handles user authentication and consent, and the result is an access token

The application may access a Kangaroo Rewards API after it receives the access token.

>**Note:** Your application should always use HTTPS in this scenario.

**1. Request Authorization**
The URL used when authenticating a user is `https://api.kangaroorewards.com/oauth/authorize`. This endpoint is accessible over SSL, and HTTP connections are refused.

Auth Code Request Endpoint

`https://api.kangaroorewards.com/oauth/authorize`

The set of query string parameters supported by the Kangaroo Authorization Server for client-side applications are:

<table class="table">
    <tr class="bg-primary">
        <th>Parameter</th> <th>Values</th> <th>Description</th>
    </tr>
    <tr>
        <td><strong>client_id</strong></td>
        <td>The client ID you obtain from the <a href="/developers">Developer Portal</a> when you registered your app</td>
        <td>
            Identifies the client that is making the request.
            The value passed in this parameter must exactly match the value shown in the <a href="/developers">Developer Portal</a>
        </td>
    </tr>
    <tr>
        <td><strong>redirect_uri</strong></td>
        <td>The URL in your application where users will be sent after authorization. </td>
        <td>
            Determines where the response is sent. The value of this parameter must exactly
            match the url listed for this app in the <a href="/developers">Developer Portal</a> (including the http or https scheme, case, and trailing '/').
        </td>
    </tr>
    <tr>
        <td><strong>response_type</strong></td>
        <td><strong>code</strong></td>
        <td>
            Must be set to "code" to request an authorization code.
        </td>
    </tr>
    <tr>
        <td><strong>scope</strong></td>
        <td>Space-delimited set of permissions that the application requests.</td>
        <td>
            A space delimited list of scopes. Identifies the Kangaroo API access that your application is requesting.
            The values passed in this parameter inform the consent screen that is shown to the user.
            There is an inverse relationship between the number of permissions requested and the likelihood of
            obtaining user consent. For information about available scopes, <a href="#scopes">see scopes</a>.
        </td>
    </tr>
    <tr>
        <td><strong>state</strong></td>
        <td>Random string</td>
        <td>Optional. This parameter is optional but highly recommended. You should store the value of the CSRF token in the user’s session to be validated when they return.</td>
    </tr>
</table>

All of these parameters will be validated by the authorization server.

The user will then be asked to login to the authorization server and approve the client.

An example URL is shown below
```
https://api.kangaroorewards.com/oauth/authorize?client_id=12345
&redirect_uri=https://example.com/callback
&response_type=code
&scope=admin
```
**2. Handling the OAuth 2.0 server response**

If the user approves the client they will be redirected from the authorisation server back to the client (specifically to the redirect URI) with the following parameters in the query string:

- *code* with the authorization code
- *state* with the state parameter sent in the original request. You should compare this value with the value stored in the user’s session to ensure the authorization code obtained is in response to requests made by this client rather than another client application.

An error response:
```
https://example.com/callback?error=access_denied&state={CSRF}
```

An authorization code response:
```
https://example.com/callback?code=OtHIETVfgY4lQz9IlTx7E3HPmuCVQb8IubZ
```

After the web server receives the authorization code, it can exchange the authorization code for an access token.

**3. Request Access Token**

The client will now send a **POST** request to the authorization server with the following parameters:

Access Token Request Endpoint:
```
https://api.kangaroorewards.com/oauth/token
```

<table class="table">
    <tr class="bg-primary">
        <th>Parameter</th> <th>Values</th> <th>Description</th>
    </tr>
    <tr>
        <td><strong>client_id</strong></td>
        <td>The client ID you obtain from the <a href="/developers">Developer Portal</a> when you registered your app</td>
        <td>
            Identifies the client that is making the request.
            The value passed in this parameter must exactly match the value shown in the <a href="/developers">Developer Portal</a>
        </td>
    </tr>
    <tr>
        <td><strong>client_secret</strong></td>
        <td>The client secret you obtain from the <a href="/developers">Developer Portal</a> when you registered your app</td>
        <td>
            Identifies the client that is making the request.
            The value passed in this parameter must exactly match the value shown in the <a href="/developers">Developer Portal</a>
        </td>
    </tr>
    <tr>
        <td><strong>redirect_uri</strong></td>
        <td>The URL in your application where users will be sent after authorization. </td>
        <td>
            Determines where the response is sent. The value of this parameter must exactly
            match the url listed for this app in the <a href="/developers">Developer Portal</a> (including the http or https scheme, case, and trailing '/').
        </td>
    </tr>
    <tr>
        <td><strong>grant_type</strong></td>
        <td><strong>authorization_code</strong></td>
        <td>
            The authorization code
        </td>
    </tr>
    <tr>
        <td><strong>code</strong></td>
        <td>Authorization code</td>
        <td>
           The code you received as a response to <a href="#oauth-step1">Step 1</a>
        </td>
    </tr>
</table>

Example Access Token Endpoint

```
> POST /oauth/token HTTP/2
> Host: api.kangaroorewards.com
> User-Agent: curl/7.65.1
> Accept: application/x-www-form-urlencoded
> Content-Type: application/x-www-form-urlencoded
> X-Application-Key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
> Content-Length: 366

| grant_type=authorization_code&client_id=12345&client_secret=8fysa8dfds9fj283&code=def502009ac5c81&redirect_uri=https://example.com/callback&scope=admin
```

Example with curl

```bash
curl -v -X POST https://api.kangaroorewards.com/oauth/token \
   -H "Accept: application/x-www-form-urlencoded" \
   -H "Content-Type: application/x-www-form-urlencoded" \
   -H "X-Application-Key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9..." \
   -d "grant_type=authorization_code \
        &code=def502009ac5c81 \
        &client_id=12345 \
        &client_secret=8fysa8dfds9fj283 \
        &redirect_uri=https://example.com/callback \
        &scope=admin"
```

By default, the response will take the following form:

```
access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1N&scope=admin&token_type=Bearer
```

A successful response is returned as a JSON array, similar to the following:

```json
{
"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImI5ZTk0NTRkYTRmOTY5Y2U2ZTUxMmFlMTRkZTdkMWJhZWQ1NjUyZTcwNmNiOTk2YTE2MjdhMjg0ZDMzMTM2NDNlZmJlZjhiZWU4YWQxMDg4In0",
"refresh_token":"2riNuUlbhlW1MWKb4Jos9FOYgIzz5ZJtK7rQjIgLDu3XsgblD5Xtn44sFieo",
"expires_in":3920,
"token_type":"Bearer"
}
```

**4. Use Access Token**
Now you may use the access token to make requests, on behalf of the user, from the resource server via the API (endpoint: https://api.kangaroorewards.com).

The access token may be used until it expires (24 hours after being issued) or is otherwise invalidated (e.g. user revoked or refresh token used).

Example Access Token Use
```bash
curl -H "Authorization: Bearer 12345678900987654321-abc34135acde13f13530" https://api.kangaroorewards.com/customers
```

#### OAuth - Refresh The Access Token Flow

Access tokens have limited lifetimes. If your application needs access to the Kangaroo API beyond the lifetime of a single access token, it can 
obtain a refresh token. A refresh token allows your application to obtain new access tokens.

If you would like to request a new access token (and new refresh token), you may do so by sending the authorization server a token refresh request. 
A typical reason for refreshing a token is that the original access token has expired. A refresh token may only be used once, 
and using it invalidates the access token that it was issued with.

**Use Refresh Token grant type**

Use the refresh_token in your token refresh request, which is a POST request to the token endpoint with the appropriate parameters.

```
https://api.kangaroorewards.com/oauth/token
```

|Parameter|Values|Description|
|-----|-----|-----------|
|**grant_type**|`refresh_token`|Must be set to "refresh_token" for an token refresh request.|
|**refresh_token**|`def502009d9337d94c8b7d67b05b9d05afb1b6...`|The **refresh_token** that was received with the original access token.|
|**client_id**|Your client ID|The value passed in this parameter must exactly match the value shown in the <a href="/developers">Developer Portal</a>|
|**client_secret**|Your client secret|The client secret you obtain from the <a href="/developers">Developer Portal</a>|
|**scope**|`admin`|A list of scopes. Currently we support only one scope, "admin"|

Example Refresh Token Request

```
Headers
> Content-Type: application/x-www-form-urlencoded
> X-Application-Key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...

POST https://api.kangaroorewards.com/oauth/token?grant_type=refresh_token
&refresh_token=def502009d9337d94c8b7d67b05b9d05afb1b6
&client_id=12345
&client_secret=8fysa8dfds9fj283
&scope=admin
```

**Token Refresh Response**

The refresh token response looks just like the normal access token grant. It includes new access and refresh tokens.

Example Refresh Token Request

```bash
curl --request POST \
  --url http://api.kangaroorewards.com/oauth/token \
  --header 'content-type: application/x-www-form-urlencoded' \
  --header 'x-application-key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9' \
  --data 'grant_type=refresh_token&refresh_token=def50200ceef1ff4664d517&client_id=1111&client_secret=cJ57RFk2CibH4o2INJb3L6&scope=admin'

```

**Store the Refresh Token**

The application should store the refresh token for future use and use the access token to access the Kangaroo API. Once the access token expires, 
the application uses the refresh token to obtain a new one.


>**Note:** Save refresh tokens in secure long-term storage and continue to use them as long as they remain valid. 

**Refresh token expiration**

You must write your code to anticipate the possibility that a granted refresh token might no longer work. A refresh token might stop working for one of these reasons:

- The user has revoked your app's access.
- The refresh token has not been used for 30 days.

>**Note:** A Refresh Token will expire in 30 days. After 30 days the Refresh Token MUST be refreshed or a new Refresh Token can be obtained by requesting a new Access Token


#### OAuth - Password Credentials Grant

The Kangaroo Rewards OAuth API also supports the Password Credentials Grant flow, where the resource owner has a trust relationship with the client.

This grant type is suitable for clients capable of obtaining the resource owner’s credentials (username and password, typically using an interactive form).

The application may access a Kangaroo Rewards API after it receives the access token.

>**Note:** Your application should always use HTTPS in this scenario.

**1. Requesting Tokens**

Access Token Request Endpoint:
```
https://api.kangaroorewards.com/oauth/token
```

Once you have created an application with type `password grant`, you may request an access token by issuing a POST request to
the `/oauth/token` route with the user's email address and password. If the request is successful, you will receive an access_token
and refresh_token in the JSON response from the server.

|Parameter|Values|Description|
|-----|-----|-----------|
|**client_id**|The client ID you obtain from the <a href="/developers">Developer Portal</a> when you registered your app|Identifies the client that is making the request. The value passed in this parameter must exactly match the value shown in the <a href="/developers">Developer Portal</a>|
|**client_secret**|The client secret you obtain from the <a href="/developers">Developer Portal</a> when you registered your app|Identifies the client that is making the request. The value passed in this parameter must exactly match the value shown in the <a href="/developers">Developer Portal</a>|
|**grant_type**|**password**|For password grant|
|**username**|john@example.com|The email address|
|**password**|YourPass$ord|The password|
|**scope**|`admin`|Scopes allow the clients to request a specific set of permissions when requesting authorization to access an account|
|**application_key**|The Application Key|The business owner has to provide The Application Key. They can get it from the business portal.|

> Note: For oauth/token endpoint the `Content-Type` header must be: `application/x-www-form-urlencoded`

Example Token Request

```php
$http = new GuzzleHttp\Client;

$response = $http->post('https://api.kangaroorewards.com/oauth/token', [
    'form_params' => [
        'grant_type' => 'password',
        'client_id' => '{YOUR_CLIENT_ID}',
        'client_secret' => '{YOUR_CLIENT_SECRET}',
        'username' => 'john@example.com',
        'password' => 'your-super-password',
        'application_key' => '{YOUR_APPLICATION_KEY}',
        'scope' => 'admin',
    ],
]);

$token = json_decode((string) $response->getBody(), true);

print_r($token);
```

Curl Example:
```
curl --request POST \
  --url https://api.kangaroorewards.com/oauth/token \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data grant_type=password \
  --data client_id={YOUR_CLIENT_ID} \
  --data client_secret={YOUR_CLIENT_SECRET} \
  --data username=john@example.com \
  --data password=your-super-password \
  --data scope=admin \
  --data application_key={YOUR_APPLICATION_KEY}
```

A successful response is returned as a JSON array, similar to the following:

```
{
    "access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImI5ZTk0NTRkYTRmOTY5Y2U2ZTUxMmFlMTRkZTdkMWJhZWQ1NjUyZTcwNmNiOTk2YTE2MjdhMjg0ZDMzMTM2NDNlZmJlZjhiZWU4YWQxMDg4In0",
    "refresh_token":"2riNuUlbhlW1MWKb4Jos9FOYgIzz5ZJtK7rQjIgLDu3XsgblD5Xtn44sFieo",
    "expires_in":3920,
    "token_type":"Bearer"
}
```


**Scopes**

Scopes limit the type of access that an access token will allow. The Kangaroo Rewards API currently supports one scope, "admin".
<table class="table">
    <tr class="bg-primary">
        <th>Name</th> <th>Description</th>
    </tr>
    <tr>
        <td><strong>(no scope)</strong></td>
        <td> Is not allowed </td>
    </tr>
    <tr>
        <td><strong>admin</strong></td>
        <td>Grants read/write access to business account, i.e. full access. This allows actions that can be requested using the GET, POST, PUT, and DELETE methods</td>
    </tr>
</table>


#### OAuth - Authorization Code Grant with PKCE

The Kangaroo Rewards OAuth API supports **PKCE** (Proof Key for Code Exchange, [RFC 7636](https://datatracker.ietf.org/doc/html/rfc7636)),
which is suitable for applications that **cannot keep a client secret confidential** — native mobile
apps, desktop and CLI tools, and browser-based single page applications. Anything shipped to a user's
device can be decompiled or inspected, so a secret embedded in it is not a secret.

These are called **public clients**. A public client is issued **no client secret**. Instead, it proves
at the token step that it is the same application that started the flow, by sending a `code_verifier`
that matches the `code_challenge` it sent at the authorization step.

PKCE is **not a separate grant type**. It is an extension of the Authorization Code flow described
above, and the token request still uses `grant_type=authorization_code`.

To register one, open the [Developer Portal](https://api.kangaroorewards.com/developers/applications),
choose **Register a new application**, and select the grant type
**"Authorization Code with PKCE (public client)"**.

**Note:** Your application should always use HTTPS in this scenario.

##### Requirements and limits

| Rule | Detail |
|------|--------|
| Client secret | Never issued. Do not send `client_secret` on any request. |
| `code_challenge_method` | **`S256` only.** `plain` is rejected with `400`, as is omitting the challenge entirely. |
| Callback URL | Must match the registered value **exactly**, including scheme, case and any trailing `/`. |
| Multiple callbacks | Supported — separate them with commas when registering. |
| Changing a callback | **Not possible after registration.** Contact support. |
| Approval | A newly registered app is inactive until the API agreement is signed and the app is approved. Until then the authorization endpoint returns `invalid_client`. |
| `X-Application-Key` | **Not required** for this grant (unlike the Password Credentials Grant). |

##### Allowed callback URL formats

| Format | Example | Use |
|--------|---------|-----|
| HTTPS | `https://app.example.com/callback` | Web and single page applications |
| Loopback | `http://127.0.0.1:8080/callback` | Desktop and CLI apps ([RFC 8252 §7.3](https://datatracker.ietf.org/doc/html/rfc8252#section-7.3)) |
| Private-use scheme | `com.example.app:/oauth2redirect` | Native mobile apps ([RFC 8252 §7.1](https://datatracker.ietf.org/doc/html/rfc8252#section-7.1)) |

A private-use scheme must be based on a domain you control (it must contain a dot), so that another
application cannot claim the same scheme and intercept your redirect. Single-label schemes such as
`myapp://` are rejected. Plain `http://` is only accepted for loopback addresses. Fragments (`#`) and
wildcards (`*`) are never accepted.

##### 1. Generate a code verifier and code challenge

Generate these **fresh for every authorization request** and keep the verifier in memory — never log
it, never reuse it, and never ship it in your app bundle.

The `code_verifier` is a cryptographically random string, 43 to 128 characters, using only
`A-Z a-z 0-9 - . _ ~`. The `code_challenge` is its SHA-256 hash, base64url-encoded without padding.

```shell
# Shell
CODE_VERIFIER=$(openssl rand -base64 48 | tr -d '\n=' | tr '+/' '-_')
CODE_CHALLENGE=$(printf '%s' "$CODE_VERIFIER" | openssl dgst -binary -sha256 | base64 | tr -d '\n=' | tr '+/' '-_')
```

```javascript
// JavaScript (browser / React Native)
const b64url = buf => btoa(String.fromCharCode(...new Uint8Array(buf)))
  .replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');

const codeVerifier = b64url(crypto.getRandomValues(new Uint8Array(48)));
const codeChallenge = b64url(
  await crypto.subtle.digest('SHA-256', new TextEncoder().encode(codeVerifier))
);
```

##### 2. Request Authorization

Redirect the user to the authorization endpoint. This endpoint is accessible over SSL, and HTTP
connections are refused.

**Auth Code Request Endpoint**

`https://api.kangaroorewards.com/oauth/authorize`

| Parameter | Values | Description |
|-----------|--------|-------------|
| `client_id` | The client ID you obtain from the Developer Portal when you registered your app | Identifies the client making the request. Must exactly match the value shown in the Developer Portal. |
| `redirect_uri` | The URL in your application where users will be sent after authorization | Must exactly match a callback URL registered for this app, including scheme, case and any trailing `/`. |
| `response_type` | `code` | Must be set to `code` to request an authorization code. |
| `code_challenge` | Base64url-encoded SHA-256 hash of your `code_verifier` | **Required.** Omitting it returns `400`. |
| `code_challenge_method` | `S256` | **Required and must be `S256`.** `plain` is rejected with `400`. |
| `scope` | Space-delimited set of permissions the application requests | Identifies the API access your application is requesting. See scopes. |
| `state` | Random string | Optional but strongly recommended. Store it in the user's session and compare it when they return. |

An example URL is shown below:

```
https://api.kangaroorewards.com/oauth/authorize?client_id=12345
    &redirect_uri=com.example.app:/oauth2redirect
    &response_type=code
    &scope=admin
    &code_challenge=v3VCKlOlN1VrEJcR_OzYwfu1yRwJGwUmMmYIFx_a3Bk
    &code_challenge_method=S256
    &state=xyzABC123
```

The user is asked to log in to the authorization server and approve the client. The consent screen
shows your application's name, the callback destination, and the permissions requested.

##### 3. Handling the OAuth 2.0 server response

If the user approves the client they are redirected to your `redirect_uri` with:

- `code` — the authorization code
- `state` — the exact value you sent. **Compare it with the value in the user's session** and discard
  the response if it does not match.

An error response:

```
com.example.app:/oauth2redirect?error=access_denied&state=xyzABC123
```

An authorization code response:

```
com.example.app:/oauth2redirect?code=def502009ac5c81&state=xyzABC123
```

If your app is not yet approved, or the `redirect_uri` does not exactly match a registered callback,
the request fails with `invalid_client` instead.

##### 4. Request Access Token

Send a `POST` to the token endpoint with your `code_verifier`. **No `client_secret` is sent** — the
verifier replaces it.

**Access Token Request Endpoint**

`https://api.kangaroorewards.com/oauth/token`

| Parameter | Values | Description |
|-----------|--------|-------------|
| `grant_type` | `authorization_code` | There is no separate "pkce" grant type. |
| `client_id` | The client ID from the Developer Portal | Identifies the client making the request. |
| `code` | Authorization code | The code you received in Step 3. |
| `redirect_uri` | The callback used in Step 2 | Must be identical to the one sent in the authorization request. |
| `code_verifier` | The verifier generated in Step 1 | Proves this is the same app that began the flow. |

**Example with curl**

```shell
curl -v -X POST https://api.kangaroorewards.com/oauth/token \
   -H "Accept: application/json" \
   -H "Content-Type: application/x-www-form-urlencoded" \
   -d "grant_type=authorization_code \
        &client_id=12345 \
        &code=def502009ac5c81 \
        &redirect_uri=com.example.app:/oauth2redirect \
        &code_verifier=2no2wxcGwRZEUFRjrCfH7K9lwqSufCVWxoTiKXU1bVLDj7ALxSoYln5ANwm_t9-a"
```

A successful response is returned as JSON:

```json
{
    "token_type": "Bearer",
    "expires_in": 86400,
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1N...",
    "refresh_token": "def50200f2b1c8a9e4..."
}
```

The authorization code is **single use**. Exchanging it twice returns:

```json
{
    "error": "invalid_grant",
    "hint": "Authorization code has been revoked"
}
```

##### 5. Refresh the access token

Refresh tokens also require no client secret for a public client.

```shell
curl -v -X POST https://api.kangaroorewards.com/oauth/token \
   -H "Accept: application/json" \
   -H "Content-Type: application/x-www-form-urlencoded" \
   -d "grant_type=refresh_token \
        &client_id=12345 \
        &refresh_token=def50200f2b1c8a9e4..."
```

##### Common errors

| Error | Cause |
|-------|-------|
| `invalid_request` — *Code challenge must be provided for public clients* | `code_challenge` was omitted. Public clients must use PKCE. |
| `invalid_request` — *Public clients must use the S256 PKCE code challenge method* | You sent `code_challenge_method=plain`. Use `S256`. |
| `invalid_client` | The app is not approved yet, or `redirect_uri` does not exactly match a registered callback. |
| `invalid_grant` — *Authorization code has been revoked* | The code was already exchanged, or it expired (codes are short-lived). |
| `invalid_grant` — *Failed to verify code_verifier* | The `code_verifier` does not match the `code_challenge` sent in Step 2. |

##### Testing in Postman

Postman's built-in OAuth 2.0 helper defaults `code_challenge_method` to **`plain`**, which Kangaroo
rejects. Set **Code Challenge Method** to **SHA-256**, or build the two requests manually as shown above.
