
# Customers

# Group Customers

## Customer Collection [/customers]

### GET

Returns a list of your customers

**Query Parameters**

<table class="table">
    <tr class="bg-default">
        <th>Name</th> <th>Type</th> <th>Description</th>
    </tr>
    <tr>
        <td>page</td>
        <td>integer</td>
        <td><strong>Optional.</strong> Provide this to retrieve the next set of results for your original query. Default value page=1</td>
    </tr>
</table>

Examples
```
GET /customers HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImFmODNk
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json
```

Response Body
```
{
    "data": [
        {
            "id": "11E696103F8FF5EABB02089E01CF89B5",
            "email": "john1@example.com",
            "phone": "5140000001",
            "first_name": "Adam",
            "last_name": "Pappas"
        },
        {
            "id": "11E696103F8FD85CBB02089E01CF89B5",
            "email": "john2@example.com",
            "phone": "5140000002",
            "first_name": "Alain",
            "last_name": "Trepanier"
        }
        . . .
    ],
    "cursor": {
        "count": 100,
        "next": 2,
        "next_uri": "/customers?page=2"
    },
    "meta": {
        "total": 145
    }
}
```

+ Request (application/json)

    + Headers

            Authorization: Bearer <access_token>
            Accept: application/vnd.kangaroorewards.api.v1+json;

+ Response 200 (application/json)
    + Attributes
        - data (array[Customer])

### POST

Create a new customer.

Body parameters
<table class="table">
    <tr class="bg-green">
        <th>Name</th> <th>Type</th> <th>Description</th>
    </tr>
    <tr>
        <td>email</td>
        <td>string</td>
        <td><strong>Required.</strong> Required if no phone number provided</td>
    </tr>
    <tr>
        <td>phone</td>
        <td>string</td>
        <td><strong>Required.</strong> Required if no email provided</td>
    </tr>
    <tr>
        <td>country_code</td>
        <td>string</td>
        <td><strong>Required.</strong> The customer's country, in ISO 3166-1-alpha-2 format.</td>
    </tr>
    <tr>
        <td>first_name</td>
        <td>string</td>
        <td><strong>Optional.</strong> First Name</td>
    </tr>
    <tr>
        <td>last_name</td>
        <td>string</td>
        <td><strong>Optional.</strong> Last Name</td>
    </tr>
    <tr>
        <td>language</td>
        <td>string</td>
        <td><strong>Optional.</strong> Communication language. Possible values <code>en</code> - English, <code>fr</code> - French, <code>es</code> - Spanish </td>
    </tr>
    <tr>
        <td>gender</td>
        <td>string</td>
        <td><strong>Optional.</strong> Possible values <code>male</code>, <code>female</code> </td>
    </tr>
</table>

Example

```
POST /customers HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImFmODNk
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json

{ "email" : "john2@example.com", "first_name": "John", "last_name": "Doe" }
```

Respone Body
```
{
    "data": {
        "id": "11e69610410894b2bb02089e01cf89b5",
        "email": "johndoe@example.com",
        "phone": "5140000001",
        "first_name": "John",
        "last_name": "Doe"
    }
}
```

+ Request (application/json)

    + Headers

            Authorization: Bearer <access_token>
            Accept: application/vnd.kangaroorewards.api.v1+json;

    + Attributes (Customer Create)

+ Response 200 (application/json)
    + Attributes
        - data (Customer)

+ Response 400 (application/json)
    + Attributes (Error 400)

+ Response 422 (application/json)
    + Attributes (Error 422)

## Customer Resource [/customers/{id}]

### GET

Returns a single customer.

Path Parameters
<table class="table">
    <tr class="bg-default">
        <th>Name</th> <th>Type</th> <th>Description</th>
    </tr>
    <tr>
        <td>customer_id</td>
        <td>string</td>
        <td><strong>Required.</strong> The ID of the customer</td>
    </tr>
</table>

Query Parameters
<table class="table">
    <tr class="bg-default">
        <th>Name</th> <th>Type</th> <th>Description</th>
    </tr>
    <tr>
        <td>include</td>
        <td>array</td>
        <td><strong>Optional. </strong>You can optionally request that the response include the balance object. To do so, specify include[]=balance in your request.</td>
    </tr>
</table>

Example
```
GET /customers/11e69610400894b2bb02089e01cf89b5?include[]=balance HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImFmODNk
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json
```

Response Body
```
{
    "data": {
        "id": "11e69610400894b2bb02089e01cf89b5",
        "email": "johndoe@example.com",
        "phone": "5140000001",
        "first_name": "John",
        "last_name": "Doe"
        "balance": {
            "points": 1000,
            "amount": 10.00
        }
    }
}
```

+ Parameters
    + id: `11e696103f8ff5eabb02089e01cf89b5` - The unique ID of the customer.

+ Request (application/json)
    + Headers

            Authorization: Bearer <access_token>
            Accept: application/vnd.kangaroorewards.api.v1+json;

+ Response 200 (application/json)
    + Attributes
        - data (Customer)

+ Response 404 (application/json)
    + Attributes (Error 404)

### PUT
Updates the details of an existing customer.

Body parameters
<table class="table">
        <tr class="bg-warning">
            <th>Name</th> <th>Type</th> <th>Description</th>
        </tr>
        <tr>
            <td>email</td>
            <td>string</td>
            <td><strong>Optional.</strong> The customer's email address.</td>
        </tr>
        <tr>
            <td>phone</td>
            <td>string</td>
            <td><strong>Optional.</strong> The customer's phone number.</td>
        </tr>
        <tr>
            <td>country_code</td>
            <td>string</td>
            <td><strong>Optional.</strong> Required only if phone number supplied. The customer's country, in ISO 3166-1-alpha-2 format.</td>
        </tr>
        <tr>
            <td>first_name</td>
            <td>string</td>
            <td><strong>Optional.</strong> First Name</td>
        </tr>
        <tr>
            <td>last_name</td>
            <td>string</td>
            <td><strong>Optional.</strong> Last Name</td>
        </tr>
        <tr>
            <td>language</td>
            <td>string</td>
            <td><strong>Optional.</strong> Communication language. Possible values <code>en</code> - English, <code>fr</code> - French, <code>es</code> - Spanish </td>
        </tr>
        <tr>
            <td>gender</td>
            <td>string</td>
            <td><strong>Optional.</strong> Possible values <code>male</code>, <code>female</code> </td>
        </tr>
    </table>


+ Parameters
    + id: `11e696103f8ff5eabb02089e01cf89b5` - The unique ID of the customer.

+ Request (application/json)
    + Headers

            Authorization: Bearer <access_token>
            Accept: application/vnd.kangaroorewards.api.v1+json;

    + Attributes (Customer)

+ Response 200 (application/json)
    + Attributes
        - data (Customer)

+ Response 400 (application/json)
    + Attributes (Error 400)

+ Response 404 (application/json)
    + Attributes (Error 404)

+ Response 422 (application/json)
    + Attributes (Error 422)

### DELETE
Deletes the customer with the requested id.

+ Request (application/json)
    + Headers

            Authorization: Bearer <access_token>
            Accept: application/vnd.kangaroorewards.api.v1+json;

+ Parameters
    + id: `11e696103f8ff5eabb02089e01cf89b5` - The unique ID of the customer.

+ Response 204 (application/json)

# Data Structures

## Customer (object)

+ id: `11e696103f8ff5eabb02089e01cf89b5` (string)
+ first_name: `Battery` (string) - First name for the Customer.
+ last_name: `Harris` (string) - Last name for the Customer.
+ email: `johndoe@example.com` (string)
+ phone: `5141234567` (string)
+ birth_date: `1963-03-28` (string) - Date of birth
+ gender: `male` (string) - Customer's gender. Can be male or female
+ balance
    + points: 135 (number)
    + giftcard: 21.35 (number)
+ member_since: `2016-06-09T21:04:50+00:00` (string)

## Customer Create (object)

+ first_name: `Battery` (string)
+ last_name: `Harris` (string)
+ email: `johndoe@example.com` (string, required)
+ birth_date: `1963-03-28` (string) - Date of birth
+ language: `en` (string) - Communication language. Possible values `en` - English, `fr` - French, `es` - Spanish
+ gender: `male` (string) - Customer's gender. Can be male or female

## Error 400 (object)

+ code: `400` (number)
+ error: `Bad Request` (string)
+ message: `Invalid ID supplied` (string)

## Error 404 (object)

+ code: `404` (number)
+ error: `Not found` (string)
+ message: `Customer not found` (string)

## Error 422 (object)

+ email (array)
    + `The email field is required` (string)
+ phone (array)
    + `The phone field is required` (string)

