# Customer Offers

# Group Customer Offers

## Customer Offer [/customers/{customer_id}/offers]

### List all offers [GET]

List all offers for a customer. This includes all types of offers:
Points Multiplier, Free Product, Bonus Points, Regular/Basic offer (discount, free item, points) that a customer can choose from. 
Each offer might have a list of actions for that customer. 

- Basic Offer (coupon) - `type_id: 8,9,10`
- Points Multiplier - `type_id: 1`
- Free Product  - `type_id: 2`
- Bonus Points - `type_id: 3`

[See all Offer Types](#offer_types)

**Path Parameters**
|Name|Type|Description|
|-----|----|-----------|
|customer_id|string|Required. The ID of the customer|

**Query Parameters**
|Name|Type|Description|
|-----|----|-----------|
|relationships|enum|`Optional.` You can optionally request that the response include the branch object. To do so, specify relationships=branch in your request.|
|coupon_type_id|mixed|`Optional.` This parameter filters offers based on their type, allowing users to specify the category of offers they want to view, such as pending, claimed, or convertible|
|per_page|integer|`Optional.` Provide this to set the number of items in the page. Default value 15; Maximum value 100|
|page|integer|`Optional.` Provide this to retrieve the next set of results for your original query. Default value page=1|


Example

```
GET /customers/12e6a34f8e89eb1e9708089e01cf89b5/offers HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
X-Application-Key: eyXai0XD7SLLzaOeJW
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json
```

Response Body
```
{
  "data": [
    {
        "id": 552,
        "points": 0,
        "expires_at": "2017-04-01T03:59:59+0000",
        "discount_value": 0,
        "multip_factor": 2,
        "real_value": 0,
        "type": "points_multiplier",
        "title": "Multiply your points",
        "description": "Come on Monday and Multiply your points",
        "images": [...],
        "actions": [
            {
                "type": "get_coupon"
            }
        ]
    }
  ]
}
```

**Coupon Types**

- `coupon_type_id: 74` - Regular coupon percentage, amount or free item - available for redemption
- `coupon_type_id: 75` - Regular coupon percentage, amount or free item - redeemed
- `coupon_type_id: 91` - Convertible coupon available for redemption
- `coupon_type_id: 92` - Convertible coupon redeemed

Filtering by specific type can be done using the `coupon_type_id` query string parameter:

`/customers/{id}/offers` - Show all offers for a customer, including targeted, claimable, or previously claimed/redeemed.

`coupon_type_id=eq|74` - Show only regular offers that are pending to claim/redeem.

`coupon_type_id=in|74,91` - Show only regular offers and convertible coupons that are pending to claim/redeem.

`coupon_type_id=eq|75` - Show only regular offers that were previously claimed/redeemed.

`coupon_type_id=not_in|74,75,91,92` - Show all offers that are not pending to claim and not previously claimed.


**Relationships**

> **NOTE:** You could also request more information using relationship parameter. All possible values:
> - **branch** - includes branch object in the response

The value of the relationships parameter MUST be a comma-separated (",") list of relationship names.

Example
```
GET /customers/12e6a34f8e89eb1e9708089e01cf89b5/offers?relationships=branch HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
Accept: application/vnd.kangaroorewards.api.v1+json;
X-Application-Key: eyXai0XD7SLLzaOeJW
Content-Type: application/json
```

Response Body
```
{
  "data": [
    "id": 123,
    "points": 0,
    "expires_at": "2017-07-01T03:59:59+0000",
    "discount_value": 0,
    "multip_factor": 0,
    "real_value": 0,
    "type": "free_product",
    "title": "Offer Title",
    "description": "",
    "images": [...],
    "branch": {
      "id": "11e6a34f8e89eb0e9708089e01cf89b5",
      "name": "Pizza Nova",
      "web_site": null,
      "logo": {
        "large": null,
        "medium": null,
        "thumbnail": null
      },
      "cover_photo": {
        "large": null,
        "medium": null,
        "thumbnail": null
      }
    }
  ]
}
```

+ Parameters
    + customer_id: `12e6a34f8e89eb1e9708089e01cf89b5` (required, string) - ID of the customer

+ Request
    + Headers

            Authorization: Bearer <access_token>
            Accept: application/vnd.kangaroorewards.api.v1+json;
            X-Application-Key: <your_application_key>

+ Response 200 (application/json)
    + Attributes
        - data (Customer Offers Base)


# Data Structures

## Customer Offers Base (array)

+ (object)
    * id: 111
    * title: `Offer Title` (string)
    * points: 3000
    * type: `free_product` (string)
    * description: `Some Offer Description` (string)
    * expires_at: `2027-06-27T02:59:59+00:00` (string)
    * multip_factor: 2 (number)
+ (object)
    * id: 112
    * title: `Offer Title 2` (string)
    * points: 50000
    * type: `free_product` (string)
    * description: `Some Offer Description` (string)
    * expires_at: `2027-04-27T02:59:59+00:00` (string)
    * multip_factor: 0 (number)
