
# Branches

# Group Branches

### GET /branches

This endpoint retrieves a list of all physical branches associated with the business. By default, virtual branches are excluded from the response. 
To include virtual branches in the result, use the `include` parameter.

**Query Parameters**

|Name|Type|Description|
|-----|----|-----------|
|page|integer|`Optional.` Provide this to retrieve the next set of results for your original query. Default value page=1|
|per_page|integer|`Optional.` Provide this to set the number of items in the page. Default value 15; Maximum value 100|
|include|string|`Optional.` Optionally include extra resources in the response. Ex: virtual_branch|

Example

```
GET /branches HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
X-Application-Key: eyXai0XD7SLLzaOeJW
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json
```

Response Body
```
{
  "data": [
    {
      "id": "11e696103f8ff5eabb02089e01cf89b5",
      "name": "Retrorant",
      "address": {
        "formatted": "1060 Boulevard Robert-Bourassa",
        "city": "Montreal",
        "region": "Quebec",
        "country": "Canada",
        "lat": 45.485169,
        "long": -73.580989
      }
    }
  ]
}
```

Example request including virtual branches (E-commerce)

```
GET /branches?include=virtual_branch HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
X-Application-Key: eyXai0XD7SLLzaOeJW
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json
```

+ Request
    + Headers

            Authorization: Bearer <access_token>
            X-Application-Key: eyXai0XD7SLLzaOeJW
            Accept: application/vnd.kangaroorewards.api.v1+json;

+ Response 200 (application/json)
    + Attributes
        - data (array[Branch Base])

# Data Structures

## Branch Base (object)

+ id: `11e696103f8ff5eabb02089e01cf89b5` (string)
+ name: `Retrorant (Gauchetiere)` (string)
+ address
    + formatted: `1060 Boulevard Robert-Bourassa` (string)
    + city: Montreal (string)
    + region: Quebec (string)
    + country: Canada (string)
    + lat: `45.4851685` (number)
    + long: `-73.5809891` (number)
