
# Customer Consents

# Group Customer Consents

## Customer Consent Collection [/customers/{customer_id}/consents{?page}]

### Retrieve consent records [GET]

List all consent records for a customer

**Path Parameters**
|Name|Type|Description|
|-----|----|-----------|
|customer_id|string|Required. The ID of the customer|

+ Parameters
    + customer_id: `12e6a34f8e89eb1e9708089e01cf89b5` (required, string) - ID of the customer

+ Request (application/json)

    + Headers

            Authorization: Bearer <access_token>
            X-Application-Key: eyXai0XD7SLLzaOeJW
            Accept: application/vnd.kangaroorewards.api.v1+json;

+ Response 200 (application/json)
    + Attributes
        - data (array[Customer Consent Base])

## Customer Consent Collection [/customers/{customer_id}/consents]

### Create a consent [POST]

Create a consent record for a customer

**Path Parameters**
|Name|Type|Description|
|-----|----|-----------|
|customer_id|string|Required. The ID of the customer|


*Body parameters*
|Name|Type|Description|
|-----|----|-----------|
|allow_sms|boolean|`Required` true or false|
|allow_email|boolean|`Required` true or false|
|allow_push|boolean|`Required` true or false|

> **NOTE:** In order to update the consent for a customer
> a new consent must be created 

Example:

```
POST /customers/11eb5b4433edf7bfaaffb42e99312ac8/consents HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC...
X-Application-Key: eyXai0XD7SLLzaOeJW...
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json

{
  "allow_sms": false,
  "allow_email": true,
  "allow_push": true
}
```

Response Body
```
{
  "data": {
    "id": 123,
    "allow_sms": false,
    "allow_email": true,
    "allow_push": true
  }
}
```

+ Parameters
    + customer_id: `11e696103f8ff5eabb02089e01cf89b5` - The unique ID of the customer.

+ Request
    + Headers

            Authorization: Bearer <access_token>
            X-Application-Key: eyXai0XD7SLLzaOeJW
            Accept: application/vnd.kangaroorewards.api.v1+json;

    + Body

            {
                "allow_email": true,
                "allow_sms": false,
                "allow_push": true
            }

+ Response 200 (application/json)
    + Attributes
        - data (Customer Consent Base)

# Data Structures

## Customer Consent Base (object)

+ allow_email: `true` (boolean)
+ allow_sms: `false` (boolean)
+ allow_push: `true` (boolean)
