
# Rewards

# Group Rewards

### GET /rewards

Provides the details for all of a business's rewards.

Example

```
GET /rewards HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json
```

Response Body
```
{
  "data": {
    [
      {
        "id": 123,
        "points": 500,
        "title": "Download Kangaroo App and Earn",
        "description": "",
        "images": []
      }
    ]
  }
}
```

+ Request
    + Headers

            Authorization: Bearer <access_token>
            Accept: application/vnd.kangaroorewards.api.v1+json;

+ Response 200 (application/json)
    + Attributes
        - data (Rewards Base)

# Data Structures

## Reward Base (object)

+ (object)
    * id: 123
    * title: `$20 Discount` (string)
    * points: 3000

## Rewards Base (array)

+ (object)
    * id: 123
    * title: `$10 Discount` (string)
    * points: 1000
+ (object)
    * id: 124
    * title: `$20 Discount` (string)
    * points: 3000

<!-- + custom_rewards (array)
    + (object)
        + id: 123
        + title: `Download Kangaroo App and Earn` (string)
        + points: 150 -->
<!-- + catalog_items (array) -->