
# Rewards

# Group Rewards

### GET /rewards

Provides the details for all of a business's rewards.

Example

```
GET /rewards HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json
```

Response Body
```
{
    "data": {
        "custom_rewards": [
            {
                "id": 35,
                "units": 500,
                "title": "Download Kangaroo App and Earn",
                "description": "",
                "images": []
            }
        ]
    }
}
```

+ Request
    + Headers
    
            Authorization: Bearer <access_token>
            Accept: application/vnd.kangaroorewards.api.v1+json;

+ Response 200 (application/json)
    + Attributes
        - data (Rewards Base)

# Data Structures

## Rewards Base (object)

+ custom_rewards (array)
    + id: 123
    + title: `Download Kangaroo App and Earn` (string)
    + units: 150
+ catalog_items (array)
    + id: 345
    + title: `$20 Discount` (string)
    + units: 3000