
# Transactions

# Group Transactions

### POST /transactions

Create a new transaction: Reward, Redeem, Refund

*Body parameters*
|Name|Type|Description|
|-----|----|-----------|
|type|string|Transaction Type: `reward`, `redeem` or `refund`|
|amount|number|Required if none of `points`, *visits* are present|
|points|number|Required if none of `amount`, *visits* are present|
|visits|number|Required if none of `amount`, *points* are present|
|customer|object|Required. The customer object and at least `id`, `email` or `phone` must be provided|
|customer.id|string|Required if none of `customer.email`, `customer.phone` are present|
|customer.email|string|Required if none of `customer.id`, `customer.phone` are present|
|customer.phone|string|Required if none of `customer.email`, `customer.phone` are present|
|employee|object|Optional. The customer object and at least `id`, `email` or `phone` must be provided|
|employee.id|string|Optional. If provided, the Employee will be attached to the transaction|
|employee.pin_code|number|Optional. Required only if the rule: "*Employee must enter his ID when Purchase Amount exceeds ...*" is active. It will override the employee.id|
|branch.id|string|Optional. To set the physical location where the transaction took place. By default it will be the main branch|

>**Note:**
>Transaction type is required and must be: `reward`, `redeem` or `refund`

>**Note:**
>One of the following attributes is required `amount`, `points` or `visits`

>**Note:**
>To apply visits aggregation set `visits` value greater than 1. The Employee PIN code is also required.

>**Note:**
>Customer is required and at least `id`, `email` or `phone` is required

Example

```
GET /transactions HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json

{
    "type": "reward",
    "amount": 5.25,
    "customer": {
        "id": "11e696103f8ff5eabb02089e01cf89b5"
    }
}
```

Response Body
```
{
    "data": {
        "id": 256560,
        "created_at": "2017-03-06T20:19:24+0000",
        "amount": 5.25,
        "units": 5,
        "name": "Reward"
    }
}
```

>**Note:**
>When `employee.pin_code` is supplied, the Employee that has that Pin Code will override the Employee attached to the transaction

Example with Employee PIN Code required and Product Rewards
```
GET /transactions HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json

{
    "type": "reward",
    "amount": 3,
    "customer": {
        "phone": "6043345025"
    },
    "employee":{
        "pin_code": "3333"
    },
    "product_rewards": [
        {
          "id": 123,
          "quantity": 3
        },
        {
          "id": 124,
          "quantity": 1
        }
    ]
}
```

Response Body with relations
```
{
    "data": {
        "id": 256775,
        "created_at": "2017-03-08T21:15:54+0000",
        "amount": 3,
        "units": 3,
        "name": "Reward",
        "offers": [
            {
                "id": 558,
                "units": 0,
                "expires_at": "2017-04-01T03:59:59+0000",
                "discount_value": 0,
                "multip_factor": 0,
                "real_value": 25,
                "type": "free_product",
                "title": "Free product",
                "description": "Free product"
            }
        ],
        "customer": {
            "id": "11e6fd0b9882cd0d84a5089e01cf89b5",
            "email": "",
            "phone": "6043345025",
            "first_name": "John",
            "last_name": "Doe",
            "member_since": "2017-03-08T21:15:54+0000",
            "balance": {
                "units": 259,
                "amount": 2.59
            }
        }
    }
}
```


>**Note:**
>You could pass the `branch.id` - wich will define where the transaction took place.

Example with Branch ID
```
GET /transactions HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json

{
    "type": "reward",
    "amount": 3,
    "customer": {
        "id": "11e696103f8ff5eabb02089e01cf89b5"
    },
    "branch":{
        "id": "11e7038ade3780aca64e089e01cf89b5"
    }
}
```

>**Note:**
>To attach an Employee to the transaction, you must set the `employee.id` in the payload

Example with Branch ID
```
GET /transactions HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json

{
    "type": "reward",
    "amount": 3,
    "customer": {
        "id": "31e692103f8ef5eabd02089e01cf89b4"
    },
    "branch":{
        "id": "11e696101aab59a4bb02089e01cf89b5"
    },
    "employee":{
        "id": "21e3038a5e3780aca24e089e01cf84b2"
    }
}
```

+ Request
    + Headers
    
            Authorization: Bearer <access_token>
            Accept: application/vnd.kangaroorewards.api.v1+json
            Content-Type: application/json

    + Attributes (Reward Amount Create)

+ Response 200 (application/json)
    + Attributes
        - data (Reward Response)

+ Response 400 (application/json)
    + Attributes (Transactions Error 400)

+ Response 422 (application/json)
    + Attributes (Transactions Error 422)

+ Request
    + Headers
    
            Authorization: Bearer <access_token>
            Accept: application/vnd.kangaroorewards.api.v1+json
            Content-Type: application/json

    + Attributes (Reward With Products Create)

+ Response 200 (application/json)
    + Attributes
        - data (Reward Response With Customer)

+ Response 400 (application/json)
    + Attributes (Transactions Error 400)

+ Response 422 (application/json)
    + Attributes (Transactions Error 422)

# Data Structures

## Reward Amount Create(object)

+ type: `reward` (string)
+ amount: `5.25` (number)
+ customer
    + id: `11e696103f8ff5eabb02089e01cf89b5` (string)

## Reward With Products Create(object)

+ type: `reward` (string)
+ amount: `5.25` (number)
+ customer
    + email: `john@example.com` (string)
+ product_rewards (array)
    + (object) 
        * id: 123 (number) 
        * quantity: 3 (number)
    + (object) 
        * id: 124 (number) 
        * quantity: 1 (number)

## Reward Response(object)

+ id: `256559` (number)
+ amount: `5.25` (number)
+ units: `5` (number)
+ name: `Reward` (string)
+ created_at: `2017-03-06T19:45:47+0000` (string)

## Reward Response With Customer (object)

+ id: `256559` (number)
+ amount: `5.25` (number)
+ units: `5` (number)
+ name: `Reward` (string)
+ created_at: `2017-03-06T19:45:47+0000` (string)
+ customer (object)
    + id: `11e6fd0b9882cd0d84a5089e01cf89b5` (string)
    + email: john@example.com (string)
    + balance (object)
        + units: 259 (number)
        + amount: 2.59 (number)

## Transactions Error 422 (object)

+ customer.id (array)
    + `The selected customer.id is invalid.` (string)

## Transactions Error 400 (object)

+ error (object)
    + status_code: 400 (number)
    + message: Bad Request (string)
    + description: Invalid Employee ID (string)
    + link: https://api.kangaroorewards.local/docs (string)


