
# Customer Actions

# Group Customer Actions

### POST /customers/{id}/actions

Trigger an action for a customer

*Body parameters*
|Name|Type|Description|
|-----|----|-----------|
|resource|string|`Required` One of the following: `tier_level`, `reward`|
|type|string|`Required` One of the following: `recalculate`, `calculate`|
|intent|string|`Required with resource=reward` One of the following: `reward`, `reward_store_credit`|
|amount|number|`Optional` Used only with resource=reward.|
|points|integer|`Optional` Used only with resource=reward.|
|visits|integer|`Optional` Used only with resource=reward.|
|branch.id|string|`Optional` Used only with resource=reward.|
|product_rewards|array|`Optional` Used only with resource=reward.|
|product_rewards.id|integer|`Optional` Used only with resource=reward.|
|product_rewards.quantity|integer|`Optional` Used only with resource=reward.|

>**Note:**
>One of the following attributes is required `amount`, `points` or `visits` when intent is: `reward`

>**Note:**
>If an offer type points multiplier is available and all the conditions are met:
> - Must be available at the specified branch
> - The amount spent is between minimum and maximum purchase amount configured for the offer
> - Offer frequency
>
> the points will be calculated and returned in the response for offer_reward.points attribute

>**Note:**
> The branch.id is optional and will be used only to calculate the points if an offer is available at the specific branch.
> 
> Default: main branch if no branch ID is passed

Example: recalculate tier level

```
POST /customers/11eb5b4433edf7bfaaffb42e99312ac8/actions HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC...
X-Application-Key: eyXai0XD7SLLzaOeJW...
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json

{
  "type": "recalculate",
  "resource": "tier_level"
}
```

Response Body
```
{
  "data": {
    "tier_progress": {
      "total_amount": null,
      "total_points": null,
      "total_visits": 10,
      "left_amount": null,
      "left_points": null,
      "left_visits": 5,
      "tiers_relation": 0,
      "start_date": "2021-01-01T00:00:00+00:00",
      "end_date": "2022-12-31T23:59:59+00:00",
      "tier_level": "VIP",
      "next_tier_level": "Platinum",
      "tier_progress": 1
    }
  }
}
```

Example: Calculate points the customer will earn based on amount spent. An offer might be applied if available at the main branch

```
POST /customers/11eb5b4433edf7bfaaffb42e99312ac8/actions HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC...
X-Application-Key: eyXai0XD7SLLzaOeJW...
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json

{
  "type": "calculate",
  "resource": "reward",
  "intent": "reward",
  "amount": 20
}
```

Example: Calculate points the customer will earn based on amount spent and product rewards

Response Body
```
POST /customers/11eb5b4433edf7bfaaffb42e99312ac8/actions
{
  "type": "calculate",
  "resource": "reward",
  "intent": "reward",
  "amount": 20,
  "product_rewards": [
    {
      "id": 123,
      "quantity": 1
    }
  ]
}
```

Example: Calculate points the customer will earn based on amount spent and offer applied if available at the specific branch

Response Body
```
POST /customers/11eb5b4433edf7bfaaffb42e99312ac8/actions
{
  "type": "calculate",
  "resource": "reward",
  "intent": "reward",
  "amount": 20,
  "branch": {
    "id":"11eac6c914dfbc4e8478b42e99312ac8"
  }
}
```

Response:
```
{
  "data": {
    "basic_reward": {
      "points": 30,
      "amount_spent": 30,
      "amount_original": 30
    },
    "product_reward": {
      "points": 0
    },
    "offer_reward": {
      "points": 10
    },
    "total_points": 40
  }
}
```

Example: Calculate store credit the customer would earn

Response Body
```
POST /customers/11eb5b4433edf7bfaaffb42e99312ac8/actions
{
  "type": "calculate",
  "resource": "reward",
  "intent": "reward_store_credit",
  "amount": 20
}
```

+ Parameters
    + id: `11e696103f8ff5eabb02089e01cf89b5` - The unique ID of the customer.

+ Request
    + Headers

            Authorization: Bearer <access_token>
            X-Application-Key: eyXai0XD7SLLzaOeJW
            Accept: application/vnd.kangaroorewards.api.v1+json;

    + Body

            {
                "type": "recalculate",
                "resource": "tier_level"
            }

+ Response 200 (application/json)
    + Attributes
        - data (Customer Action Base)

# Data Structures

## Customer Action Base (object)

+ tier_progress (object)
    + total_amount: `0` (number)
    + total_points: `100` (number)
    + tier_level: `VIP` (string)

