# Offers

# Group Offers

## Offer [/offers]

### Create offer [POST]

An offer contains information about a free product, percent-off or amount-off discount you might want to apply to a customer. 
Currently 4 main types of offers can be created:
- Basic Offer (coupon) type_id: 8,9,10
- Points Multiplier type_id: 1
- Free Product  type_id: 2
- Bonus Points type_id: 3

Basic Offers can be claimed as coupoons and after that, the coupon can be redeemed.
See #Offer Types

> **NOTE:** Offer images MUST be uploaded first using POST /offers/images endpoint, before creating an offer
> Images must be uploaded to Kangaroo Rewards. External images are not allowed

*Body parameters* common for all offer types
|Name|Type|Description|
|-----|----|-----------|
|type_id|integer|`Required` Offer Type. Possible options: `1` - Points Multiplier, `2` - Free Product, `3` - Bonus Points, `8` - Basic Offer (Free product), `9` - Basic Offer (percent-off), `10` - Basic Offer (amount-off)|
|targeted_offer_flag|integer|`Required` (0,1) Default 1 - targeted customers, 0 - available for everyone|
|never_expires_flag|integer|`Optional` Default 0 - expires_at is required, 1 - the offer will never expire|
|publish_at|string|`Optional` Default current date and time. ISO 8601 date. Example: `2000-07-01T00:00:00+00:00`|
|expires_at|string|`Required` if never_expires_flag = 0. ISO 8601 date. Example: `2000-07-01T00:00:00+00:00`|
|images|array|`Required` Up to 4 items|
|images.*.original|string,url|`Required` The uploaded image path, max: 255|
|images.*.large|string,url|`Required` The uploaded image path, max: 255|
|images.*.*medium|string,url|`Required` The uploaded image path, max: 255|
|images.*.thumbnail|string,url|`Required` The uploaded image path, max: 255|
|available_at_branches|array|`Required` - A list of branches where the offer is available at. At least one branch is required|
|available_at_branches.*.id|string|`Required` Branch ID|
|offer_languages|array|`Required` - At least English is required, language_id = 1|
|offer_languages.*.language_id|integer|`Required` - 1 - English, 2 - French, 3 - Spanish|
|offer_languages.*.offer_title|string|`Required` - Offer title in that language. max: 255|
|offer_languages.*.offer_description|string|`Optional` - Offer description in that language. max 500|
|offer_languages.*.offer_terms_conditions|string|`Optional` - Terms and conditions. max: 1000|
|offer_languages.*.offer_link|string,url|`Optional` - An external link for offer. max: 100|


*Body parameters* specific for Basic Offer only

All common +

|Name|Type|Description|
|-----|----|-----------|
|coupon_auto_get|integer|`Optional` (0,1) Default 0 - Must click "Get Coupon" on the App, 1 - The coupon will be auto-claimed|
|coupon_perm_available|integer|`Optional` (0,1) Default 0 - Not permanently available, 1 - Permanently available|
|coupon_expires_in|integer|`Optional`- The number of days the coupon must be claimed before it will expire. Default 0 - never expires, > 0 Coupon must be claimed within x days |
|discount_value|numeric|`Required` if type_id is 9 or 10 - amount off > 0 or percent off > 0 and <=100 |


*Body parameters* specific for Points Multiplier Offer

All common +

|Name|Type|Description|
|-----|----|-----------|
|offer_frequency_id|integer|`Required` Default 1. Possible options: 1 - Daily, 2 - Weekly, 3 - Specific day and time, 4 - Once|
|multip_factor|numeric|`Required` Multiplication factor > 0. Example: 2 - 2x the points, 1.5 - 1.5x the points|
|min_purchase|numeric|`Required` - Minimum purchase amount >= 0|
|max_purchase|numeric|`Required` - Maximum purcase amount, cannot be less than min purchase amount|
|apps_only|boolean|`Optional` Default false. If true - Customers must log in with QR code to be eligible|
|freq_details|array|`Required` when offer frequency id is `3` (Specific day and time). Must be an array in the following format: ["1","2","3","4","5","6","7"]|
|peak_from|string,time|`Required` with frequncy details. 24-hour format of an hour with leading zeros and minutes with leading zeros. Min: 00:00, max: 23:59. Must be before peak_to Ex: "09:00"|
|peak_to|string,time|`Required` with frequncy details. 24-hour format of an hour with leading zeros and minutes with leading zeros. Min: 00:00, max: 23:59. Must be after peak_from Ex: "17:45"|

> **NOTE:** freq_details field must be an array in the following format: ["1","2","3","4","5","6","7"]
> containing the days of the week from Monday to Sunday as numbers. Where 
> 1 - Monday, 2 - Tuesday ... 7 - Sunday
> Example: ["1","2"] - available only on Monday and Tuesday
> Example: ["5"] - available only on Friday


*Body parameters* specific for Free Product Offer

All common + Points Multiplier Offer (exept multip_factor) +

|Name|Type|Description|
|-----|----|-----------|
|offer_languages.*.offer_product|string|`Required` - Product description. max: 255|


*Body parameters* specific for Bonus Points Offer

All common + Points Multiplier Offer (exept multip_factor) +

|Name|Type|Description|
|-----|----|-----------|
|points|integer|`Required` - Bonus points to offer|

Example creating a Basic Offer
```
POST /offers HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC...
Accept: application/vnd.kangaroorewards.api.v1+json;
X-Application-Key: eyXai0XD7SLLzaOeJW...
Content-Type: application/json

{
  "type_id": 9,
  "targeted_offer_flag": 0,
  "expires_at": "2020-07-17T18:10:05-00:00",
  "never_expires_flag": 0,
  "discount_value": 10,
  "offer_languages": [
    {
      "language_id": 1,
      "offer_title": "10% OFF today",
      "offer_description": "Available only for today",
      "offer_terms_conditions": "",
      "offer_link": "https://example.com/some-offer"
    }
  ],
  "available_at_branches": [
    {
      "id": "11eaa5c938ec36cc9df9b42e99312ac8"
    },
    {
      "id": "12eac6c914dfbc4e8478b42e99312ac5"
    }
  ],
  "images": [
      {
        "original": "https://www.kangaroorewards.com/photos/image.png",
        "large": "https://www.kangaroorewards.com/photos/image1.png",
        "medium": "https://www.kangaroorewards.com/photos/image2.png",
        "thumbnail": "https://www.kangaroorewards.com/photos/image3.png"
      }
    ]
}
```

Example creating a Points Multiplier Offer
```
POST /offers HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC...
Accept: application/vnd.kangaroorewards.api.v1+json;
X-Application-Key: eyXai0XD7SLLzaOeJW...
Content-Type: application/json

{
  "type_id": 1,
  "offer_frequency_id" : 3,
  "multip_factor": 2,
  "min_purchase": 10,
  "max_purchase": 1000,
  "apps_only": false,
  "freq_details": ["1","2","5"],
  "peak_from": "09:00",
  "peak_to": "17:30",
  "targeted_offer_flag": 0,
  "expires_at": "2020-07-17T18:10:05-04:00",
  "never_expires_flag": 0,
  "offer_languages": [
    {
      "language_id": 1,
      "offer_title": "2x the points on Monday and Tuesday"
    }
  ],
  "available_at_branches": [
    {
      "id": "11eaa5c938ec36cc9df9b42e99312ac8"
    }
  ],
  "images": [
      {
        "original": "https://www.kangaroorewards.com/photos/image.png",
        "large": "https://www.kangaroorewards.com/photos/image1.png",
        "medium": "https://www.kangaroorewards.com/photos/image2.png",
        "thumbnail": "https://www.kangaroorewards.com/photos/image3.png"
      }
    ]
}
```

+ Request (application/json)
    + Headers

            Authorization: Bearer <access_token>
            Accept: application/vnd.kangaroorewards.api.v1+json;
            X-Application-Key: <your_application_key>

    + Attributes (CreateBasicOfferData)

+ Response 200 (application/json)
    + Attributes
        - data (Offer)

+ Response 422 (application/json)
    + Attributes (Offer Error 422)

+ Response 403 (application/json)
    + Attributes (Create Offer Error 403)

+ Response 400 (application/json)
    + Attributes (Create Offer Error 400)


### List all offers [GET]

List all offers, including expired and targeted

Query Parameters
|Name|Type|Description|
|-----|----|-----------|
|relationships|enum|`Optional.` You can optionally request that the response include the branch object. To do so, specify relationships=branch in your request.|
|page|int|`Optional.` The page number|
|per_page|int|`Optional.` Items per page|
|products.product_sku|string|`Optional.` Filter by product SKU|
|pos_items_group.tag_name|string|`Optional.` Filter by product tag name|


**Offer Types**

- type_id: 1 - Points Multiplier
- type_id: 2 - Free product
- type_id: 3 - Bonus points
- type_id: 8 - Basic offer (coupon). Type free product (can be used as a coupon)
- type_id: 9 - Basic offer (coupon). Type discount in % (can be used as a coupon)
- type_id: 10 - Basic offer (coupon). Type discount in $ (can be used as a coupon)
- type_id: 14 - Gift card

> **NOTE:** Only offers type ID 8,9,10  can be used as coupons
> A coupon MUST be assigned to customer before it will be available for redemption
> In order to assign a coupon to a customer create a transaction with intent: `get_coupon`, customer and offer object

Example

```
GET /offers HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
X-Application-Key: eyXai0XD7SLLzaOeJW
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json
```

Response Body
```
{
  "data": [
    {
      "id": 552,
      "points": 0,
      "expires_at": "2017-04-01T03:59:59+0000",
      "discount_value": 0,
      "multip_factor": 2,
      "real_value": 0,
      "type": "points_multiplier",
      "title": "Multiply your points",
      "description": "Come on Monday and Multiply your points",
      "images": [...]
    }
  ]
}
```

**Relationships**

> **NOTE:** You could also request more information using relationship parameter. All possible values:
> - **branch** - includes branch object in the response

The value of the relationships parameter MUST be a comma-separated (",") list of relationship names.

Example
```
GET /offers?relationships=branch HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
Accept: application/vnd.kangaroorewards.api.v1+json;
X-Application-Key: eyXai0XD7SLLzaOeJW
Content-Type: application/json
```

Response Body
```json
{
  "data": [
    "id": 123,
    "points": 0,
    "expires_at": "2017-07-01T03:59:59+0000",
    "discount_value": 0,
    "multip_factor": 0,
    "real_value": 0,
    "type": "free_product",
    "title": "Offer Title",
    "description": "",
    "images": [
      {
        "default": true,
        "path": "1498064009_594aa4895e8c7.jpg"
      }
    ],
    "branch": {
      "id": "11e6a34f8e89eb0e9708089e01cf89b5",
      "name": "Pizza Nova",
      "web_site": null,
      "logo": {
        "large": null,
        "medium": null,
        "thumbnail": null
      },
      "cover_photo": {
        "large": null,
        "medium": null,
        "thumbnail": null
      }
    }
  ]
}
```

Filter offers by product SKU

```GET /offers?products.product_sku=eq|SKERR23423SF9SD934I```

Filter offers by product tag name

```GET /offers?pos_items_group.tag_name=eq|promo```


+ Request
    + Headers

            Authorization: Bearer <access_token>
            Accept: application/vnd.kangaroorewards.api.v1+json;
            X-Application-Key: <your_application_key>

+ Response 200 (application/json)
    + Attributes
        - data (Offers Base)


## Offer [/offers/{offer_id}]

+ Parameters
    + offer_id: me (required, number) - ID of the Offers

### Retrieve an offer [GET]

Returns a single offer.

Path Parameters
|Name|Type|Description|
|-----|----|-----------|
|offer_id|number|`Required.` The ID of the offer|

Query Parameters
|Name|Type|Description|
|-----|----|-----------|
|relationships|enum|`Optional.` You can optionally request that the response include related objects. To do so, specify for example: relationships=branch in your request.|


Example
```
GET /offers/{offer_id}?relationships=branch HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
Accept: application/vnd.kangaroorewards.api.v1+json;
X-Application-Key: eyXai0XD7SLLzaOeJW
Content-Type: application/json
```

Response Body
```
{
  "data": {
    "id": 123,
    "points": 0,
    "expires_at": "2017-07-01T03:59:59+0000",
    "discount_value": 0,
    "multip_factor": 0,
    "real_value": 0,
    "type": "free_product",
    "title": "Offer Title",
    "description": "",
    "images": [
      {
        "default": true,
        "large": "1498064009_594aa4895e8c7.jpg"
      }
    ],
    "branch": {
      "id": "11e6a34f8e89eb0e9708089e01cf89b5",
      "name": "Pizza Nova",
      "web_site": null,
      "logo": {
        "large": null,
        "medium": null,
        "thumbnail": null
      },
      "cover_photo": {
        "large": null,
        "medium": null,
        "thumbnail": null
      }
    }
  }
}
```

+ Parameters
    + offer_id: `123` - The unique ID of the offer.

+ Request (application/json)
    + Headers

            Authorization: Bearer <access_token>
            Accept: application/vnd.kangaroorewards.api.v1+json;
            X-Application-Key: <your_application_key>

+ Response 200 (application/json)
    + Attributes
        - data (Offer)

+ Response 404 (application/json)
    + Attributes (Offer Error 404)


### Update an offer [PUT]

Update an offer.

Path Parameters
|Name|Type|Description|
|-----|----|-----------|
|offer_id|number|`Required.` The ID of the offer|

> **NOTE:** `type_id` cannot be changed.\
> All fields can be updated similar to creating except `type_id` and `offer_id`\
> On update all fields are optional.

Example updating an offer
```
PUT /offers/123 HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC...
Accept: application/vnd.kangaroorewards.api.v1+json;
X-Application-Key: eyXai0XD7SLLzaOeJW...
Content-Type: application/json

{
  "targeted_offer_flag": 0,
  "expires_at": "2020-07-17T18:10:05-00:00",
  "never_expires_flag": 0,
  "discount_value": 10,
  "offer_languages": [
    {
      "language_id": 1,
      "offer_title": "10% OFF today",
      "offer_description": "Available only for today",
      "offer_terms_conditions": "",
      "offer_link": "https://example.com/some-offer"
    }
  ],
  "available_at_branches": [
    {
      "id": "11eaa5c938ec36cc9df9b42e99312ac8"
    },
    {
      "id": "12eac6c914dfbc4e8478b42e99312ac5"
    }
  ],
  "images": [
        {
        "original": "https://www.kangaroorewards.com/photos/image.png",
        "large": "https://www.kangaroorewards.com/photos/image1.png",
        "medium": "https://www.kangaroorewards.com/photos/image2.png",
        "thumbnail": "https://www.kangaroorewards.com/photos/image3.png"
        }
    ]
}
```

Example updating only title
```
PUT /offers/123 HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC...
Accept: application/vnd.kangaroorewards.api.v1+json;
X-Application-Key: eyXai0XD7SLLzaOeJW...
Content-Type: application/json

{
  "offer_languages": [
    {
      "language_id": 1,
      "offer_title": "10% OFF today"
    }
}
```

+ Parameters
    + offer_id: `123` - The unique ID of the offer.

+ Request (application/json)
    + Headers

            Authorization: Bearer <access_token>
            Accept: application/vnd.kangaroorewards.api.v1+json;
            X-Application-Key: <your_application_key>

    + Attributes (UpdateBasicOfferData)

+ Response 200 (application/json)
    + Attributes
        - data (Offer)

+ Response 422 (application/json)
    + Attributes (Offer Error 422)

+ Response 403 (application/json)
    + Attributes (Create Offer Error 403)

+ Response 400 (application/json)
    + Attributes (Create Offer Error 400)

+ Response 404 (application/json)
    + Attributes (Offer Error 404)

### Delete an offer [DELETE]

Delete an offer

Path Parameters
|Name|Type|Description|
|-----|----|-----------|
|offer_id|number|`Required.` The ID of the offer|

Example
```
DELETE /offers/123 HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC...
Accept: application/vnd.kangaroorewards.api.v1+json;
X-Application-Key: eyXai0XD7SLLzaOeJW
Content-Type: application/json
```

+ Parameters
    + offer_id: `123` - The unique ID of the offer.

+ Request (application/json)
    + Headers

            Authorization: Bearer <access_token>
            Accept: application/vnd.kangaroorewards.api.v1+json;
            X-Application-Key: <your_application_key>

+ Response 204 (application/json)
    + Attributes

+ Response 403 (application/json)
    + Attributes (Create Offer Error 403)

+ Response 404 (application/json)
    + Attributes (Offer Error 404)


# Data Structures

## Offer (object)

+ id: 552 (number)
+ points: 0 (number)
+ expires_at: `2017-04-01T03:59:59+0000` (string)
+ discount_value: 0 (number)
+ multip_factor: 2 (number)
+ real_value: 0 (number)
+ type_id: 8 (number) - The offer type ID
+ type: `points_multiplier` (string)
+ title: `Multiply your points` (string)
+ description: `Come on Monday and Multiply your points` (string)
+ images (array)
    + (object)
        + original: `https://www.kangaroorewards.com/photos/image.png` (string)
        + large: `https://www.kangaroorewards.com/photos/image1.png` (string)
        + medium: `https://www.kangaroorewards.com/photos/image2.png` (string)
        + thumbnail: `https://www.kangaroorewards.com/photos/image3.png` (string)
        + `default`: true (boolean)


## Offers Base (array)

+ (object)
    * id: 111
    * title: `Offer Title` (string)
    * points: 3000
    * type_id: 1 (number) - The offer type ID
    * type: `free_product` (string)
    * description: `Some Offer Description` (string)
    * expires_at: `2027-06-27T02:59:59+00:00` (string)
    * multip_factor: 2 (number)
+ (object)
    * id: 112
    * title: `Offer Title 2` (string)
    * points: 50000
    * type_id: 2 (number) - The offer type ID
    * type: `free_product` (string)
    * description: `Some Offer Description` (string)
    * expires_at: `2027-04-27T02:59:59+00:00` (string)
    * multip_factor: 0 (number)

## CreateBasicOfferData

+ type_id: 8 (number) - The offer type ID 8,8,10
+ offer_frequency_id: 1 (number) - Daily, weekly, specific day and time
+ targeted_offer_flag: 1 (number) - 0 Available for everyone, 1 Targeted
+ publish_at: `2020-04-01T03:59:59+0000` (string) - When the offer will be published
+ expires_at: `2020-04-01T03:59:59+0000` (string)
+ never_expires_flag: 1 (number) - 1 the offer will never expire, 0 it will expire
+ discount_value: 10 (number)
+ offer_languages (array)
    + (object)
        + language_id: 1 (number) - Language ID. 1 - English is required
        + title: `Free coffee` (string) - max: 255
        + description: `Come on Monday and get a free coffee` (string) - max: 500
        + offer_terms_conditions: `Offer terms and conditions here` (string) - max: 1000
        + offer_link: `https://example.com/some-offer-link` (string) - max: 500
+ images (array)
    + (object)
        + original: `https://www.kangaroorewards.com/photos/image.png` (string)
        + large: `https://www.kangaroorewards.com/photos/image1.png` (string)
        + medium: `https://www.kangaroorewards.com/photos/image2.png` (string)
        + thumbnail: `https://www.kangaroorewards.com/photos/image3.png` (string)
+ available_at_branches (array)
    + (object)
        + id: 1es8uwrs8sd9fsf9 (string) - Branch ID

## UpdateBasicOfferData

+ offer_frequency_id: 1 (number) - Daily, weekly, specific day and time
+ targeted_offer_flag: 1 (number) - 0 Available for everyone, 1 Targeted
+ publish_at: `2020-04-01T03:59:59+0000` (string) - When the offer will be published
+ expires_at: `2020-04-01T03:59:59+0000` (string)
+ never_expires_flag: 1 (number) - 1 the offer will never expire, 0 it will expire
+ discount_value: 10 (number)
+ offer_languages (array)
    + (object)
        + language_id: 1 (number) - Language ID. 1 - English is required
        + title: `Free coffee` (string) - max: 255
        + description: `Come on Monday and get a free coffee` (string) - max: 500
        + offer_terms_conditions: `Offer terms and conditions here` (string) - max: 1000
        + offer_link: `https://example.com/some-offer-link` (string) - max: 500
+ images (array)
    + (object)
        + original: `https://www.kangaroorewards.com/photos/image.png` (string)
        + large: `https://www.kangaroorewards.com/photos/image1.png` (string)
        + medium: `https://www.kangaroorewards.com/photos/image2.png` (string)
        + thumbnail: `https://www.kangaroorewards.com/photos/image3.png` (string)
+ available_at_branches (array)
    + (object)
        + id: 1es8uwrs8sd9fsf9 (string) - Branch ID

## Offer Error 404 (object)

+ error (object)
    - status_code: 404 (number)
    - message: `Offer 112 Not Found` (string)
    - description: `The requested resource doesn't exist.` (string)

## Create Offer Error 403 (object)

+ message: `This action is unauthorized.` (string)

## Create Offer Error 400 (object)

+ error (object)
    - status_code: 400 (number)
    - message: `Bad Request` (string)
    - description: `Expiration date cannot be prior to publish date.` (string)

## Offer Error 422 (object)

+ type_id (array)
    + `Type id is required.` (string)
+ images (array)
    + `The images may not have more than 4 items.` (string)
+ offer_languages (array)
    + `Offer languages is required.` (string)
