
# Product Rewards
With Product Rewards (À La Carte Rewards) customers can earn points when purchasing specific products

# Group Product Rewards

### GET /product-rewards

List Product Rewards.

**Query Parameters**

|Name|Type|Description|
|-----|----|-----------|
|page|integer|`Optional.` Provide this to retrieve the next set of results for your original query. Default value page=1|
|per_page|integer|`Optional.` Provide this to set the number of items in the page. Default value 15; Maximum value 100|
|relationships|enum|`Optional.` You can optionally request that the response include the product object. To do so, specify relationships=product in your request.|

Example

```
GET /product-rewards HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json
```

Response Body
```
{
  "data": [
        {
            "id": 123,
            "points": 300
        }
    ]
}
```

Example with Product

```
GET /product-rewards?relationships=product HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json
```

Response Body
```
{
  "data": [
    {
        "id": 123,
        "points": 300,
        "product": {
            "id": 120348,
            "title": "Product Reward 1",
            "description": "",
            "images": []
        }
    }
  ]
}
```

+ Request
    + Headers

            Authorization: Bearer <access_token>
            Accept: application/vnd.kangaroorewards.api.v1+json;

+ Parameters
     + relationships (string, optional) - Include relationships in the response. Example `relationships=product`
        + Default: null

+ Response 200 (application/json)
    + Attributes
        - data (ProductRewards Base)

# Data Structures

## ProductReward Base (object)

- id: 123 (number)
- points: 3000 (number)
+ product (object)
    - id: 123 (number)
    - title: `Product Reward 2` (string)
    - description: `Product Reward Description` (string)

## ProductRewards Base (array)

+ (object)
    * id: 123
    * points: 1000 (number)
    + product (object)
        - id: 123 (number)
        - title: `Product Reward 1` (string)
        - description: `Product Reward Description` (string)
+ (object)
    * id: 124
    * points: 3000 (number)
    + product (object)
        - id: 124 (number)
        - title: `Product Reward 2` (string)
        - description: `Product Reward Description` (string)
