# Questions

# Group Questions

## Questions [/questions{?page}]

### Create a question [POST]

*Body parameters*
|Name|Type|Description|
|-----|----|-----------|
|email|string|`Optional` Between 1 and 255 characters in length|
|first_name|string|`Optional` Between 1 and 255 characters in length|
|body|string|`Required` Minimum 15 characters|
|product_id|string|`Optional` Required if the type is 1 - product review|
|type|integer|`Required` (1, 2) 1: product question, 2: website question |
|source|integer|`Required` (1, 2) The platform where the question was left. 1: website page, 2: review widget |

Example create a question

```
POST /questions HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
X-Application-Key: eyXai0XD7SLLzaOeJW
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json
X-Store-Domain: example.com

{
    "email": "lisa@example.com",
    "first_name": "Lisa",
    "body": "What are the key features and benefits of this product?",
    "type": 1,
    "source": 1,
    "product_id": "5157526"
}
```

+ Request (application/json)
    + Headers

            Authorization: Bearer <access_token>
            X-Application-Key: <X-Application-Key>
            Accept: application/vnd.kangaroorewards.api.v1+json;
            X-Store-Domain: <store_domain>;


    + Attributes (QuestionCreate)
+ Response 200 (No Content)

+ Response 401 (application/json)
    + Attributes (Questions Error 401)

+ Response 422 (application/json)
    + Attributes
        + body (array)
            + `The body field is required.` (string)
        + source (array)
            + `The source field is required.` (string)

# Group Question Replies

## Question Replies [/questions/{id}/replies]

+ Parameters
    + id: `603b051e-9ba0-49cf-a111-b9f622c5c9a6` (string) - The question id.

### Create a reply [POST]

Creates a new reply to a question.

*Body parameters*
|Name|Type|Description|
|-----|----|-----------|
|body|string|`Required` Reply content|
|email|string|`Optional`|

Example create a reply

```
POST /questions/603b051e-9ba0-49cf-a111-b9f622c5c9a6/replies HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
X-Application-Key: eyXai0XD7SLLzaOeJW
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json
X-Store-Domain: example.com

{
    "body": "Reply",
    "email": "john@example.com"
}
```


+ Request (application/json)
    + Headers

            Authorization: Bearer <access_token>
            X-Application-Key: <X-Application-Key>
            Accept: application/vnd.kangaroorewards.api.v1+json;
            X-Store-Domain: <store_domain>;

    + Attributes (QuestionReplyCreate)
+ Response 200 (No Content)

+ Response 401 (application/json)
    + Attributes (Questions Error 401)

+ Response 403 (application/json)
    + Attributes (Questions Error 403)

+ Response 422 (application/json)
    + Attributes
        + body(array)
            + `The body field is required.` (string)

# Data Structures

## QuestionCreate(object)
+ email: `lisa@example.com` (string)
+ first_name: `Lisa` (string)
+ body: `What are the key features and benefits of this product?` (string) - question
+ product_id: `5157526` (string) - product id in the integration system
+ type: 1 (number) - 1: product question 2: general question
+ source: 1 (number) - 1: website 2: widget


## QuestionReplyCreate(object)
+ question_id: `603b051e-9ba0-49cf-a111-b9f622c5c9a6` (string) - The question id that your are trying to reply to.
+ body: `Reply` (string) - The reply content
+ email: `john@example.com` (string) - email address

## Questions Error 401 (object)

+ error (object)
    + status_code: `401` (number)
    + message: `Unauthenticated.` (string)
    + description: `Unauthenticated.` (string)

## Questions Error 403 (object)

+ error (object)
    + status_code: `403` (number)
    + message: `This action is unauthorized.` (string)
    + description: `This action is unauthorized.` (string)

## Questions Error 422 (object)

+ email (array)
    + `The email field is required.` (string)
+ body (array)
    + `The body field is required.` (string)
