# Call to actions

## Call to actions [/call-to-actions{?page}]

### List all call to actions [GET]

Returns a list of call to actions

**Query Parameters**

|Name|Type|Description|
|-----|----|-----------|
|page|integer|`Optional.` Provide this to retrieve the next set of results for your original query. Default value page=1|
|include|string|`Optional.` You can optionally include=action in your request.|

Examples
```
GET /call-to-actions HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImFmODNk
X-Application-Key: eyXai0XD7SLLzaOeJW
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json
```

Response Body
```
{
	"data": [
		{
            "id": 498,
            "enabled": 1,
            "points": 10,
            "result_freq": null,
            "result_count": 1,
            "action_freq": null,
            "action_count": 1,
            "action_duration_min": 0,
            "action_duration_unit": null,
            "conditions": null,
            "action_id": 6,
            "created_at": "2023-01-28T18:33:37+00:00"
        },
        {
            "id": 499,
            "enabled": 1,
            "points": 10,
            "result_freq": null,
            "result_count": 1,
            "action_freq": null,
            "action_count": 1,
            "action_duration_min": 0,
            "action_duration_unit": null,
            "conditions": null,
            "action_id": 7,
            "created_at": "2023-01-29T01:37:06+00:00"
        }
	],
	"links": {
		"first": "http://api.kangaroorewards.com/call-to-actions?page=1",
		"last": null,
		"prev": null,
		"next": null
	},
	"meta": {
		"current_page": 1,
		"from": 1,
		"path": "http://api.kangaroorewards.com/call-to-actions",
		"per_page": 15,
		"to": 2
	}
}
```
**Filtering**

Supported Fields:
- `action_id` - Filter by action id
- `action_required` - Filter by action required
- `action_enabled` - Filter by enabled

Operators:
- `gt` - Greater Than
- `gte` - Greater Than or Equal
- `lt` - Less Than
- `lte` - Less Than or Equal
- `eq` - Equal
- `in` - Match any value in the list. Separated by comma.


Example
```
GET /call-to-actions?action_id=eq%7C1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
Accept: application/vnd.kangaroorewards.api.v1+json;
X-Application-Key: eyXai0XD7SLLzaOeJW
Content-Type: application/json
```

Response Body
```
{
	"data": [
		{
            "id": 481,
            "enabled": 1,
            "points": 100,
            "result_freq": null,
            "result_count": 0,
            "action_freq": null,
            "action_count": 1,
            "action_duration_min": 0,
            "action_duration_unit": null,
            "conditions": null,
            "action_id": 1,
            "created_at": "2015-12-07T23:21:37+00:00"
        }
	],
	"links": {
		"first": "https://api.kangaroorewards.com/call-to-actions?page=1",
		"last": null,
		"prev": null,
		"next": null
	},
	"meta": {
		"current_page": 1,
		"from": 1,
		"path": "https://api.kangaroorewards.com/call-to-actions",
		"per_page": 15,
		"to": 1
	}
}
```


## Call to actions [/call-to-actions]

### Create a call to action [POST]

A call to action is a single action where a customer earns points.

*Body parameters* common for all actions
|Name|Type|Description|
|-----|----|-----------|
|action_id|number|Required. 3: Check-in, 4: Follow Facebook, 5: Complete user profile. 6: Follow Twitter, 7: Follow Instagram, 8: Follow Tiktok|
|result_count|number|Optional. The maximum times to trigger the results. Default is 0, means unlimited.|
|result_freq|string|Optional. The frequency with which the result should be repeated. In: hourly,daily,weekly,monthly,yearly.|
|action_count|number|Optional. How many times the action should be taken for triggering the result. Default: 1|
|action_freq|string|Optional. The frequency with which the event should be repeated. In: hourly,daily,weekly,monthly,yearly.|
|action_duration_min|number|Optional. |
|action_duration_unit|string|Optional. In:minute,hour,day,week,month,year|

*Body parameters* specific for complete profile action
All common +

|Name|Type|Description|
|-----|----|-----------|
|conditions.requires|array|Required when action_id is 5. Customer profiles need to be filled to reward the action.|
|conditions.requires.*|string|Required when action_id is 5, In: first,last,birth_date,address,postal_code,consent,custom_field_1,custom_field_2,custom_field_3,custom_field_4,custom_field_5. |


Example create follow facebook action

```
POST /call-to-actions HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
X-Application-Key: eyXai0XD7SLLzaOeJW
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json

{
  "action_id": 4,
  "points" : 15,
  "result_count": 1
}
```
Example create complete profile action

```
POST /call-to-actions HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
X-Application-Key: eyXai0XD7SLLzaOeJW
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json

{
  "action_id": 5,
  "points" : 15,
  "result_count": 1
  "conditions":
      {
        "requires": [
            "first",
            "last",
            "birth_date",
            "address",
            "postal_code",
            "consent",
            "custom_field_1",
            "custom_field_2"
        ]
      }
}
```
### Update a call to action [PATCH]

*Body parameters* common for all actions
|Name|Type|Description|
|-----|----|-----------|
|result_count|number|Optional. The maximum times to trigger the results. Default is 0, means unlimited.|
|result_freq|string|Optional. The frequency with which the result should be repeated. In: hourly,daily,weekly,monthly,yearly.|
|action_count|number|Optional. How many times the action should be taken for triggering the result. Default: 1|
|action_freq|string|Optional. The frequency with which the event should be repeated. In: hourly,daily,weekly,monthly,yearly.|
|action_duration_min|number|Optional. |
|action_duration_unit|string|Optional. In:minute,hour,day,week,month,year|

*Body parameters* specific for complete profile action
All common +

|Name|Type|Description|
|-----|----|-----------|
|conditions.requires|array|Optional. when action_id is 5. Customer profiles need to be filled to reward the action.|
|conditions.requires.*|string|Optional. when action_id is 5, In: first,last,birth_date,address,postal_code,consent,custom_field_1,custom_field_2,custom_field_3,custom_field_4,custom_field_5. |


Example update follow facebook action

```
PATCH /call-to-actions/108 HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
X-Application-Key: eyXai0XD7SLLzaOeJW
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json

{
  "points" : 200,
  "result_count": 1
}
```

### Delete a call to action [DELETE]

Example Delete follow facebook action

```
DELETE /call-to-actions/108 HTTP/1.1
Host: api.kangaroorewards.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLC
X-Application-Key: eyXai0XD7SLLzaOeJW
Accept: application/vnd.kangaroorewards.api.v1+json;
Content-Type: application/json
```



